In [1]:
import pandas as pd

import functions

pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv('C:/Users/aprataso/Downloads/final_data/Clustering/cluster_data_num2.csv')

basket = pd.read_csv('C:/Users/aprataso/Downloads/final_data/Gold/basket_treated.csv')

prod = pd.read_csv('C:/Users/aprataso/Downloads/final_data/Gold/prod_treated.csv')

In [3]:
# Apply deserialization
basket['product_id'] = basket['product_id'].apply(functions.deserialize_list)

In [4]:
prod

,product_id,manufacturer,department,brand,commodity_desc,sub_commodity_desc,curr_size_of_product,curr_size_of_product_value,curr_size_of_product_units,brand_bin
0,25671,2,Groceries,National,FRZN ICE,ICE - CRUSHED/CUBED,22 LB,22.0,LB,True
1,26081,2,MISC. TRANS.,National,NO COMMODITY DESCRIPTION,NO SUBCOMMODITY DESCRIPTION,,NaN,,True
2,26093,69,Bakery,Private,BREAD,BREAD:ITALIAN/FRENCH,,NaN,,False
3,26190,69,Groceries,Private,FRUIT - SHELF STABLE,APPLE SAUCE,50 OZ,50.0,OZ,False
4,26355,69,Groceries,Private,COOKIES/CONES,SPECIALTY COOKIES,14 OZ,14.0,OZ,False
...,...,...,...,...,...,...,...,...,...,...
92333,18293142,6384,DRUG GM,National,BOOKSTORE,PAPERBACK BOOKS,,NaN,,True
92334,18293439,6393,DRUG GM,National,BOOKSTORE,CHILDRENS LOW END,,NaN,,True
92335,18293696,6406,DRUG GM,National,BOOKSTORE,PAPERBACK BEST SELLER,,NaN,,True
92336,18294080,6442,DRUG GM,National,BOOKSTORE,PAPERBACK BOOKS,,NaN,,True
92337,18316298,764,Groceries,National,PAPER TOWELS,PAPER TOWELS & HOLDERS,,NaN,,True

In [5]:
prod = prod[['product_id', 'sub_commodity_desc']] # change wanted column here

In [6]:
prod.head(1)

   product_id   sub_commodity_desc
0       25671  ICE - CRUSHED/CUBED

In [8]:
merged_data = pd.merge(basket,
                        data['Cluster'],
                        left_on=basket['household_key'],
                        right_on=data['household_key'],
                        how='inner')

In [11]:
#merged_data = merged_data.drop('key_0', axis = 1)
merged_data = merged_data[['household_key', 'basket_id', 'product_id', 'Cluster']]
merged_data.head(2)

,household_key,basket_id,product_id,Cluster
0,1,27601281299,"[825123, 831447, 840361, 845307, 852014, 85498...",1
1,1,27774192959,"[852662, 856942, 997025, 1030547, 1049998, 105...",1

In [13]:
merged_data['Cluster'].unique()

array([1, 0, 3, 2], dtype=int64)

In [14]:
cluster_0 = merged_data.loc[merged_data['Cluster'] == 0]
cluster_1 = merged_data.loc[merged_data['Cluster'] == 1]
cluster_2 = merged_data.loc[merged_data['Cluster'] == 2]
cluster_3 = merged_data.loc[merged_data['Cluster'] == 3]

In [19]:
functions.category_rules(cluster_3, prod, 'sub_commodity_desc')


# antecedent support - proportion of transactions that contain the antecedent - HGIH
# consequent  support - proportion of transactions that contain the consequent - HIGH
# support - proportion of transactions that contain both - HIGH
# confidence - probability that the consequent is present given that the antecedent is present - HIGH
# lift -  A lift value greater than 1 indicates that the antecedent and consequent occur together more often than would be expected by chance, suggesting a positive relationship - > 1
# leverage - difference between the observed support and the expected support if the antecedent and consequent were independent - HIGH
# Conviction - how likely the rule is to be correct compared to a random occurrence - HIGH
# Zhangâ€™s Metric - association strength and the degree of dependence between the antecedent and consequent - HIGH

     support                          itemsets
4   0.230670           (FLUID MILK WHITE ONLY)
0   0.125642                         (BANANAS)
5   0.112055           (GASOLINE-REG UNLEADED)
6   0.105368          (MAINSTREAM WHITE BREAD)
12  0.102553  (SOFT DRINKS 12/18&15PK CAN CAR)
11  0.082454                 (SHREDDED CHEESE)
10  0.081765  (SFT DRNK 2 LITER BTL CARB INCL)
7   0.071002                    (POTATO CHIPS)
2   0.065723  (CANDY BARS (SINGLES)(INCLUDING)
15  0.065723  (BANANAS, FLUID MILK WHITE ONLY)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
9,(YOGURT NOT MULTI-PACKS),(BANANAS),0.049768,0.125642,0.020565,0.413222,3.288887,0.014312,1.490099,0.732395
33,(MAINSTREAM WHITE BREAD),(POTATO CHIPS),0.105368,0.071002,0.022011,0.208897,2.942125,0.014530,1.174308,0.737856
34,(POTATO CHIPS),(MAINSTREAM WHITE BREAD),0.071002,0.105368,0.022011,0.310005,2.942125,0.014530,1.296579,0.710561
40,(POTATO CHIPS),(SOFT DRINKS 12/18&15PK CAN CAR),0.071002,0.102553,0.021293,0.299891,2.924239,0.014011,1.281866,0.708323
39,(SOFT DRINKS 12/18&15PK CAN CAR),(POTATO CHIPS),0.102553,0.071002,0.021293,0.207628,2.924239,0.014011,1.172426,0.733225
10,(CHOCOLATE MILK),(FLUID MILK WHITE ONLY),0.034307,0.230670,0.022797,0.664498,2.880730,0.014884,2.293071,0.676060
16,(KIDS CEREAL),(FLUID MILK WHITE ONLY),0.049719,0.230670,0.031774,0.639079,2.770533,0.020306,2.131573,0.672494
0,(ALL FAMILY CEREAL),(FLUID MILK WHITE ONLY),0.039451,0.230670,0.025117,0.636654,2.760023,0.016017,2.117351,0.663875
1,(DAIRY CASE 100% PURE JUICE - O),(BANANAS),0.060142,0.125642,0.020652,0.343392,2.733104,0.013096,1.331629,0.674693
37,(MAINSTREAM WHITE BREAD),(SOFT DRINKS 12/18&15PK CAN CAR),0.105368,0.102553,0.028843,0.273740,2.669248,0.018038,1.235711,0.699017

In [16]:
functions.product_rules(cluster_0)

    support   itemsets
0  0.088694  (1082185)
1  0.055458  (6534178)

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, zhangs_metric]
Index: []

## TESTS

In [25]:

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import association_rules, apriori

def category_rules(cluster,prod, column):
    
    """
    Extracts frequent itemsets and association rules from a cluster of products.

    Parameters:
        cluster (DataFrame): A DataFrame representing a cluster of products.
            It should contain the following columns:
            - 'list_of_goods': A column containing lists of products in each transaction.
        categories (DataFrame): A DataFrame representing the categories of each product.
            It should contain the following columns:
            - 'product_name': A column containing the names of each product.
            - 'category': A column containing the categories of each product.

    Returns:
       None, but The function displays the frequent itemsets and association rules.

    """

    #list_products = [ast.literal_eval(product) for product in cluster['product_id'].values]
    list_products = cluster['product_id'].tolist()
    #list_categories = [[categories.loc[categories['product_id'] == item, 'department'].values[0] for item in sublist] for sublist in list_products]
    list_categories = []
    for sublist in list_products:
        category_list = []
        for item in sublist:
            # Find category for the product ID
            category = prod.loc[prod['product_id'] == item, f'{column}']
            if not category.empty:
                category_list.append(category.values[0])
            # If no category is found, skip the item
        # Only add non-empty category lists
        if category_list:
            list_categories.append(category_list)

    
    te = TransactionEncoder()
    te_fit = te.fit(list_categories).transform(list_categories)
    transactions_items = pd.DataFrame(te_fit, columns=te.columns_)

    frequent_itemsets_grocery = apriori(
    transactions_items, min_support=0.05, use_colnames=True
    )
  
    display(frequent_itemsets_grocery.sort_values(by='support', ascending=False).head(10))

    frequent_itemsets_grocery_iter = apriori(
    transactions_items, min_support=0.02, use_colnames=True
    )

    # We'll use a confidence level of 20%
    rules_grocery_iter = association_rules(frequent_itemsets_grocery_iter, 
                                  metric="confidence", 
                                  min_threshold=0.2)
  
    display(rules_grocery_iter.sort_values(by='lift', ascending=False).head(10))


    return frequent_itemsets_grocery

In [26]:
category_rules(cluster_3, prod, 'sub_commodity_desc')

    support                          itemsets
4     0.231           (FLUID MILK WHITE ONLY)
0     0.126                         (BANANAS)
5     0.112           (GASOLINE-REG UNLEADED)
6     0.105          (MAINSTREAM WHITE BREAD)
12    0.103  (SOFT DRINKS 12/18&15PK CAN CAR)
11    0.082                 (SHREDDED CHEESE)
10    0.082  (SFT DRNK 2 LITER BTL CARB INCL)
7     0.071                    (POTATO CHIPS)
2     0.066  (CANDY BARS (SINGLES)(INCLUDING)
15    0.066  (BANANAS, FLUID MILK WHITE ONLY)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
9,(YOGURT NOT MULTI-PACKS),(BANANAS),0.050,0.126,0.021,0.413,3.289,0.014,1.490,0.732
33,(MAINSTREAM WHITE BREAD),(POTATO CHIPS),0.105,0.071,0.022,0.209,2.942,0.015,1.174,0.738
34,(POTATO CHIPS),(MAINSTREAM WHITE BREAD),0.071,0.105,0.022,0.310,2.942,0.015,1.297,0.711
40,(POTATO CHIPS),(SOFT DRINKS 12/18&15PK CAN CAR),0.071,0.103,0.021,0.300,2.924,0.014,1.282,0.708
39,(SOFT DRINKS 12/18&15PK CAN CAR),(POTATO CHIPS),0.103,0.071,0.021,0.208,2.924,0.014,1.172,0.733
10,(CHOCOLATE MILK),(FLUID MILK WHITE ONLY),0.034,0.231,0.023,0.664,2.881,0.015,2.293,0.676
16,(KIDS CEREAL),(FLUID MILK WHITE ONLY),0.050,0.231,0.032,0.639,2.771,0.020,2.132,0.672
0,(ALL FAMILY CEREAL),(FLUID MILK WHITE ONLY),0.039,0.231,0.025,0.637,2.760,0.016,2.117,0.664
1,(DAIRY CASE 100% PURE JUICE - O),(BANANAS),0.060,0.126,0.021,0.343,2.733,0.013,1.332,0.675
37,(MAINSTREAM WHITE BREAD),(SOFT DRINKS 12/18&15PK CAN CAR),0.105,0.103,0.029,0.274,2.669,0.018,1.236,0.699

    support                                         itemsets
0     0.126                                        (BANANAS)
1     0.056                            (BEERALEMALT LIQUORS)
2     0.066                 (CANDY BARS (SINGLES)(INCLUDING)
3     0.060                 (DAIRY CASE 100% PURE JUICE - O)
4     0.231                          (FLUID MILK WHITE ONLY)
5     0.112                          (GASOLINE-REG UNLEADED)
6     0.105                         (MAINSTREAM WHITE BREAD)
7     0.071                                   (POTATO CHIPS)
8     0.059                                        (PREMIUM)
9     0.052                                         (PRIMAL)
10    0.082                 (SFT DRNK 2 LITER BTL CARB INCL)
11    0.082                                (SHREDDED CHEESE)
12    0.103                 (SOFT DRINKS 12/18&15PK CAN CAR)
13    0.053                                  (TOILET TISSUE)
14    0.050                           (TORTILLA/NACHO CHIPS)
15    0.066                 (BANANAS, FLUID MILK WHITE ONLY)
16    0.057  (MAINSTREAM WHITE BREAD, FLUID MILK WHITE ONLY)

In [30]:
frequent_itemsets_grocery_0 = category_rules(cluster_0, prod, 'sub_commodity_desc')
frequent_itemsets_grocery_1 = category_rules(cluster_1, prod, 'sub_commodity_desc')
frequent_itemsets_grocery_2 = category_rules(cluster_2, prod, 'sub_commodity_desc')
frequent_itemsets_grocery_3 = category_rules(cluster_3, prod, 'sub_commodity_desc')

    support                          itemsets
4     0.212           (FLUID MILK WHITE ONLY)
9     0.096  (SFT DRNK 2 LITER BTL CARB INCL)
0     0.092                         (BANANAS)
7     0.087          (MAINSTREAM WHITE BREAD)
11    0.081  (SOFT DRINKS 12/18&15PK CAN CAR)
5     0.071           (GASOLINE-REG UNLEADED)
10    0.064                 (SHREDDED CHEESE)
1     0.061             (BEERALEMALT LIQUORS)
8     0.058                    (POTATO CHIPS)
3     0.057  (DAIRY CASE 100% PURE JUICE - O)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(ALL FAMILY CEREAL),(FLUID MILK WHITE ONLY),0.032,0.212,0.021,0.675,3.184,0.015,2.423,0.708
6,(KIDS CEREAL),(FLUID MILK WHITE ONLY),0.042,0.212,0.028,0.665,3.136,0.019,2.350,0.711
3,(DAIRY CASE 100% PURE JUICE - O),(FLUID MILK WHITE ONLY),0.057,0.212,0.032,0.563,2.656,0.020,1.803,0.661
4,(EGGS - LARGE),(FLUID MILK WHITE ONLY),0.042,0.212,0.022,0.529,2.494,0.013,1.672,0.626
5,(IWS SINGLE CHEESE),(FLUID MILK WHITE ONLY),0.042,0.212,0.021,0.506,2.389,0.012,1.596,0.607
13,(YOGURT NOT MULTI-PACKS),(FLUID MILK WHITE ONLY),0.043,0.212,0.021,0.498,2.348,0.012,1.569,0.600
1,(BANANAS),(FLUID MILK WHITE ONLY),0.092,0.212,0.045,0.487,2.296,0.025,1.535,0.621
2,(FLUID MILK WHITE ONLY),(BANANAS),0.212,0.092,0.045,0.210,2.296,0.025,1.150,0.716
7,(MAINSTREAM WHEAT/MULTIGRAIN BR),(FLUID MILK WHITE ONLY),0.055,0.212,0.027,0.485,2.289,0.015,1.531,0.596
8,(MAINSTREAM WHITE BREAD),(FLUID MILK WHITE ONLY),0.087,0.212,0.042,0.482,2.275,0.023,1.522,0.614

    support                          itemsets
5     0.220           (FLUID MILK WHITE ONLY)
8     0.102          (MAINSTREAM WHITE BREAD)
0     0.097                         (BANANAS)
12    0.090  (SOFT DRINKS 12/18&15PK CAN CAR)
10    0.086  (SFT DRNK 2 LITER BTL CARB INCL)
11    0.078                 (SHREDDED CHEESE)
9     0.068                    (POTATO CHIPS)
6     0.067           (GASOLINE-REG UNLEADED)
2     0.058  (CANDY BARS (SINGLES)(INCLUDING)
3     0.055  (DAIRY CASE 100% PURE JUICE - O)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
7,(KIDS CEREAL),(FLUID MILK WHITE ONLY),0.047,0.220,0.031,0.666,3.032,0.021,2.338,0.703
3,(CHOCOLATE MILK),(FLUID MILK WHITE ONLY),0.032,0.220,0.021,0.643,2.924,0.014,2.183,0.680
0,(ALL FAMILY CEREAL),(FLUID MILK WHITE ONLY),0.035,0.220,0.022,0.632,2.878,0.014,2.122,0.676
4,(DAIRY CASE 100% PURE JUICE - O),(FLUID MILK WHITE ONLY),0.055,0.220,0.031,0.561,2.553,0.019,1.777,0.644
5,(EGGS - LARGE),(FLUID MILK WHITE ONLY),0.051,0.220,0.028,0.546,2.486,0.017,1.719,0.630
6,(IWS SINGLE CHEESE),(FLUID MILK WHITE ONLY),0.046,0.220,0.025,0.537,2.444,0.015,1.685,0.619
9,(MAINSTREAM WHITE BREAD),(FLUID MILK WHITE ONLY),0.102,0.220,0.051,0.506,2.301,0.029,1.578,0.629
10,(FLUID MILK WHITE ONLY),(MAINSTREAM WHITE BREAD),0.220,0.102,0.051,0.234,2.301,0.029,1.173,0.725
8,(MAINSTREAM WHEAT/MULTIGRAIN BR),(FLUID MILK WHITE ONLY),0.052,0.220,0.026,0.498,2.267,0.015,1.555,0.590
1,(BANANAS),(FLUID MILK WHITE ONLY),0.097,0.220,0.048,0.494,2.246,0.027,1.541,0.615

    support                          itemsets
6     0.229           (FLUID MILK WHITE ONLY)
1     0.139                         (BANANAS)
7     0.127           (GASOLINE-REG UNLEADED)
16    0.101  (SOFT DRINKS 12/18&15PK CAN CAR)
8     0.087          (MAINSTREAM WHITE BREAD)
15    0.084                 (SHREDDED CHEESE)
21    0.084  (BANANAS, FLUID MILK WHITE ONLY)
4     0.067  (DAIRY CASE 100% PURE JUICE - O)
10    0.066                    (POTATO CHIPS)
18    0.061                   (TOILET TISSUE)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
64,(TOILET TISSUE),(PAPER TOWELS & HOLDERS),0.061,0.057,0.026,0.428,7.549,0.023,1.649,0.924
65,(PAPER TOWELS & HOLDERS),(TOILET TISSUE),0.057,0.061,0.026,0.461,7.549,0.023,1.741,0.920
68,"(BANANAS, FLUID MILK WHITE ONLY)",(DAIRY CASE 100% PURE JUICE - O),0.084,0.067,0.026,0.315,4.684,0.021,1.362,0.858
71,(DAIRY CASE 100% PURE JUICE - O),"(BANANAS, FLUID MILK WHITE ONLY)",0.067,0.084,0.026,0.391,4.684,0.021,1.506,0.843
85,"(STRAWBERRIES, FLUID MILK WHITE ONLY)",(BANANAS),0.032,0.139,0.021,0.642,4.618,0.016,2.406,0.810
91,(MAINSTREAM WHITE BREAD),"(FLUID MILK WHITE ONLY, SOFT DRINKS 12/18&15PK...",0.087,0.051,0.020,0.234,4.589,0.016,1.239,0.856
90,"(FLUID MILK WHITE ONLY, SOFT DRINKS 12/18&15PK...",(MAINSTREAM WHITE BREAD),0.051,0.087,0.020,0.398,4.589,0.016,1.516,0.824
87,(STRAWBERRIES),"(BANANAS, FLUID MILK WHITE ONLY)",0.058,0.084,0.021,0.357,4.268,0.016,1.425,0.813
86,"(BANANAS, FLUID MILK WHITE ONLY)",(STRAWBERRIES),0.084,0.058,0.021,0.249,4.268,0.016,1.254,0.836
20,(BANANAS),(STRAWBERRIES),0.139,0.058,0.031,0.226,3.878,0.023,1.217,0.862

    support                          itemsets
4     0.231           (FLUID MILK WHITE ONLY)
0     0.126                         (BANANAS)
5     0.112           (GASOLINE-REG UNLEADED)
6     0.105          (MAINSTREAM WHITE BREAD)
12    0.103  (SOFT DRINKS 12/18&15PK CAN CAR)
11    0.082                 (SHREDDED CHEESE)
10    0.082  (SFT DRNK 2 LITER BTL CARB INCL)
7     0.071                    (POTATO CHIPS)
2     0.066  (CANDY BARS (SINGLES)(INCLUDING)
15    0.066  (BANANAS, FLUID MILK WHITE ONLY)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
9,(YOGURT NOT MULTI-PACKS),(BANANAS),0.050,0.126,0.021,0.413,3.289,0.014,1.490,0.732
33,(MAINSTREAM WHITE BREAD),(POTATO CHIPS),0.105,0.071,0.022,0.209,2.942,0.015,1.174,0.738
34,(POTATO CHIPS),(MAINSTREAM WHITE BREAD),0.071,0.105,0.022,0.310,2.942,0.015,1.297,0.711
40,(POTATO CHIPS),(SOFT DRINKS 12/18&15PK CAN CAR),0.071,0.103,0.021,0.300,2.924,0.014,1.282,0.708
39,(SOFT DRINKS 12/18&15PK CAN CAR),(POTATO CHIPS),0.103,0.071,0.021,0.208,2.924,0.014,1.172,0.733
10,(CHOCOLATE MILK),(FLUID MILK WHITE ONLY),0.034,0.231,0.023,0.664,2.881,0.015,2.293,0.676
16,(KIDS CEREAL),(FLUID MILK WHITE ONLY),0.050,0.231,0.032,0.639,2.771,0.020,2.132,0.672
0,(ALL FAMILY CEREAL),(FLUID MILK WHITE ONLY),0.039,0.231,0.025,0.637,2.760,0.016,2.117,0.664
1,(DAIRY CASE 100% PURE JUICE - O),(BANANAS),0.060,0.126,0.021,0.343,2.733,0.013,1.332,0.675
37,(MAINSTREAM WHITE BREAD),(SOFT DRINKS 12/18&15PK CAN CAR),0.105,0.103,0.029,0.274,2.669,0.018,1.236,0.699

In [35]:
frequent_itemsets_grocery_0['Cluster'] = 0
frequent_itemsets_grocery_1['Cluster'] = 1
frequent_itemsets_grocery_2['Cluster'] = 2
frequent_itemsets_grocery_3['Cluster'] = 3

In [45]:
frequent_itemsets_grocery_3

    support                                         itemsets  Cluster
0     0.126                                        (BANANAS)        3
1     0.056                            (BEERALEMALT LIQUORS)        3
2     0.066                 (CANDY BARS (SINGLES)(INCLUDING)        3
3     0.060                 (DAIRY CASE 100% PURE JUICE - O)        3
4     0.231                          (FLUID MILK WHITE ONLY)        3
5     0.112                          (GASOLINE-REG UNLEADED)        3
6     0.105                         (MAINSTREAM WHITE BREAD)        3
7     0.071                                   (POTATO CHIPS)        3
8     0.059                                        (PREMIUM)        3
9     0.052                                         (PRIMAL)        3
10    0.082                 (SFT DRNK 2 LITER BTL CARB INCL)        3
11    0.082                                (SHREDDED CHEESE)        3
12    0.103                 (SOFT DRINKS 12/18&15PK CAN CAR)        3
13    0.053                                  (TOILET TISSUE)        3
14    0.050                           (TORTILLA/NACHO CHIPS)        3
15    0.066                 (BANANAS, FLUID MILK WHITE ONLY)        3
16    0.057  (MAINSTREAM WHITE BREAD, FLUID MILK WHITE ONLY)        3

In [47]:
'''frequent_itemsets_grocery = pd.merge(frequent_itemsets_grocery_0,
                                     frequent_itemsets_grocery_1,
                                     how='inner',
                                     on='itemsets')

frequent_itemsets_grocery'''

,support_x,itemsets,Cluster_x,support_y,Cluster_y
0,0.092,(BANANAS),0,0.097,1
1,0.061,(BEERALEMALT LIQUORS),0,0.051,1
2,0.054,(CANDY BARS (SINGLES)(INCLUDING),0,0.058,1
3,0.057,(DAIRY CASE 100% PURE JUICE - O),0,0.055,1
4,0.212,(FLUID MILK WHITE ONLY),0,0.220,1
5,0.071,(GASOLINE-REG UNLEADED),0,0.067,1
6,0.055,(MAINSTREAM WHEAT/MULTIGRAIN BR),0,0.052,1
7,0.087,(MAINSTREAM WHITE BREAD),0,0.102,1
8,0.058,(POTATO CHIPS),0,0.068,1
9,0.096,(SFT DRNK 2 LITER BTL CARB INCL),0,0.086,1
10,0.064,(SHREDDED CHEESE),0,0.078,1
11,0.081,(SOFT DRINKS 12/18&15PK CAN CAR),0,0.090,1

In [39]:
frequent_itemsets_grocery = pd.concat([frequent_itemsets_grocery_0, 
                         frequent_itemsets_grocery_1, 
                         frequent_itemsets_grocery_2, 
                         frequent_itemsets_grocery_3], 
                        ignore_index=True)

In [41]:
frequent_itemsets_grocery['Cluster'].unique()

array([0, 1, 2, 3], dtype=int64)

In [42]:
frequent_itemsets_grocery.to_csv('C:/Users/aprataso/Downloads/final_data/Clustering/frequent_itemsets_grocery.csv', index=False)

In [23]:
# Flatten product_id lists in df2
product_ids_df2 = [item for sublist in cluster_0['product_id'] for item in sublist]

product_ids_df1 = prod['product_id'].unique()
product_ids_df2 = set(product_ids_df2)

# Find product_ids in df1 not in df2
missing_ids = [pid for pid in product_ids_df1 if pid in product_ids_df2]
missing_count = len(missing_ids)

print("Product IDs in df1 and in df2:")
print(missing_count)

Product IDs in df1 and in df2:
43647