In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
trans_prod_per_household = pd.read_csv("C:/Users/aprataso/Downloads/final_data/treated/trans_prod_per_household.csv")
hh = pd.read_csv("C:/Users/aprataso/Downloads/final_data/treated/hh_treated.csv")

In [4]:
trans_prod_per_household.head(5)

,Unnamed: 0,household_key,day,basket_id,product_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc,sales_value_eu,loyalty_card_price,non_loyalty_card_price,days_,transaction_date,manufacturer,department,brand,commodity_desc,sub_commodity_desc,curr_size_of_product,curr_size_of_product_value,curr_size_of_product_units,COUP/STR & MFG_quantity,_quantity,MEAT_quantity,PASTRY_quantity,GROCERY_quantity,MISC SALES TRAN_quantity,POSTAL CENTER_quantity,FLORAL_quantity,RESTAURANT_quantity,PORK_quantity,SPIRITS_quantity,GRO BAKERY_quantity,COSMETICS_quantity,VIDEO RENTAL_quantity,RX_quantity,CNTRL/STORE SUP_quantity,VIDEO_quantity,DAIRY DELI_quantity,CHARITABLE CONT_quantity,MEAT-PCKGD_quantity,ELECT &PLUMBING_quantity,SEAFOOD_quantity,KIOSK-GAS_quantity,HBC_quantity,DELI/SNACK BAR_quantity,PROD-WHS SALES_quantity,DELI_quantity,AUTOMOTIVE_quantity,TOYS_quantity,NUTRITION_quantity,HOUSEWARES_quantity,SEAFOOD-PCKGD_quantity,MEAT-WHSE_quantity,GARDEN CENTER_quantity,MISC. TRANS._quantity,PHOTO_quantity,PHARMACY SUPPLY_quantity,PRODUCE_quantity,SALAD BAR_quantity,TRAVEL & LEISUR_quantity,GM MERCH EXP_quantity,DRUG GM_quantity,FROZEN GROCERY_quantity,CHEF SHOPPE_quantity
0,0,1,"[51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 5...","[27601281299, 27601281299, 27601281299, 276012...","[825123, 831447, 840361, 845307, 852014, 85498...","[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, ...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",436,"[0.0, 0.0, -0.3, -0.62, -1.2, -1.3, -0.49, 0.0...",1456,8,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[4.27, 3.2, 1.17, 3.97, 2.99, 7.69, 2.68, 1.59...","[3.99, 2.99, 1.39, 4.33, 3.99, 8.49, 2.99, 1.4...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",51,2021-02-20,"[1179, 317, 69, 4084, 69, 1011, 159, 407, 2082...","['GROCERY', 'GROCERY', 'GROCERY', 'DELI', 'GRO...","['National', 'National', 'Private', 'National'...","['SALD DRSNG/SNDWCH SPRD', 'CHEESE', 'EGGS', '...","['SEMI-SOLID SALAD DRESSING MAY', 'SHREDDED CH...","['30 OZ', '8 OZ', '1 DZ', ' ', '56 OZ', ' ', '...","[30.0, 8.0, 1.0, nan, 56.0, nan, 16.0, 15.0, 2...","[' OZ', ' OZ', ' DZ', ' ', ' OZ', ' ', ' OZ', ...",0,0,5,49,1310,2,0,1,3,0,0,0,0,0,0,0,0,0,0,117,0,0,0,0,0,0,68,0,0,19,0,0,0,0,0,0,0,209,13,0,0,201,0,0
1,1,2,"[103, 103, 103, 103, 103, 103, 103, 103, 103, ...","[28210649301, 28210649301, 28210649301, 282106...","[854852, 930118, 1077555, 1098066, 5567388, 55...","[1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, ...","[0.65, 4.47, 1.0, 0.79, 2.5, 2.5, 2.5, 5.0, 3....",401,"[0.0, -5.03, -0.59, -0.2, -2.19, -2.19, -2.19,...",1904,15,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -2.5, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.7, 4.78, 1.07, 0.85, 2.68, 2.68, 2.68, 5.35...","[0.65, 9.5, 1.59, 0.99, 4.69, 4.69, 4.69, 4.69...","[0.65, 4.47, 1.0, 0.79, 2.5, 2.5, 2.5, 2.5, 3....",103,2021-04-13,"[2, 2, 69, 69, 1208, 1208, 1208, 1208, 1323, 6...","['PRODUCE', 'PRODUCE', 'GROCERY', 'GROCERY', '...","['National', 'National', 'Private', 'Private',...","['TOMATOES', 'STONE FRUIT', 'MILK BY-PRODUCTS'...","['TOMATOES HOTHOUSE ON THE VINE', 'CHERRIES RE...","['13 LB', '2 LB', '16 OZ', '11 OZ', '12OZ/12PK...","[13.0, 2.0, 16.0, 11.0, 12.0, 12.0, 12.0, 12.0...","[' LB', ' LB', ' OZ', ' OZ', 'OZ/PK', ' OZ', '...",0,0,34,11,544,2,0,1,0,0,0,0,5,0,0,0,0,0,0,23,0,0,0,0,0,0,13,0,0,3,0,1,0,0,0,0,0,87,0,0,0,110,0,0
2,2,3,"[113, 113, 113, 113, 113, 113, 113, 113, 113, ...","[28344561779, 28344561779, 28344561779, 283445...","[866211, 878996, 882830, 904360, 921345, 93194...","[1, 1, 1, 1, 3, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, ...","[3.08, 1.64, 1.29, 0.99, 5.0, 2.08, 4.0, 1.69,...",401,"[-1.04, -0.55, 0.0, 0.0, -0.97, 0.0, 0.0, 0.0,...",1549,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.3, 1.75, 1.38, 1.06, 5.35, 2.23, 4.28, 1.81...","[4.12, 2.19, 1.29, 0.99, 1.99, 1.04, 2.0, 1.69...","[3.08, 1.64, 1.29, 0.99, 1.67, 1.04, 2.0, 1.69...",113,2021-04-23,"[2, 2, 764, 673, 1094, 1377, 1071, 910, 69, 2,...","['PRODUCE', 'PRODUCE', 'GROCERY', 'PRODUCE', '...","['National', 'National', 'National', 'National...","['GRAPES', 'GRAPES', 'WAREHOUSE SNACKS', 'VEGE...","['GRAPES WHITE', 'GRAPES RED', 'CANISTER POTAT...","['18 LB', '18 LB', '5.75 OZ', '24CT', '4.5 OZ'...","[18.0, 18.0, 5.0, 24.0, 4.0, 15.0, 9.0, 20.0, ...","[' LB', ' LB', '. OZ', 'CT', '. OZ', ' OZ', ' ...",0,0,69,1,1251,0,0,0,0,0,0,0,1,0,0,0,0,0,0,113,0,0,6949,0,0,0,6,0,0,0,0,2,0,0,0,0,0,40,1,0,0,107,0,0
3,3,4,"[104, 104, 104, 104, 104, 104, 104, 104, 104, ...","[28243317097, 28243317097, 28243317097, 282433...","[836163, 857849, 877523, 878909, 883932, 89142...","[2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, ...","[3.0, 0.44, 1.79, 1.5, 1.83, 3.59, 2.0, 0.99, ...",298,"[-2.58, -0.45, 0.0, -0.09, -0.66, 0.0, -0.89, ...",1452,16,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.21, 0.47, 1.92, 1.61, 1.96, 3.84, 2.14, 1.0...","[2.79, 0.89, 1.79, 1.59, 2.49, 3.59, 2.89, 1.1...","[1.5, 0.44, 1.79, 1.5, 1.83, 3.59, 2.0, 0.99, ...",104,2021-04-14,"[586, 71, 194, 69, 586, 1075, 69, 1529, 499, 1...","['GROCERY', 'GROCERY', 'GROCERY', 'GROCERY', '...","['National', 'National', 'National', 'Private'...","['COOKIES/CONES', 'MARGARINES', 'SPICES & EXTR...","['CHOCOLATE COVERED COOKIES', 'MARGARINE STIC...","['8.5 OZ', '16 OZ', '4.4 OZ', '13OZ/12CT', '16...","[8.0, 16.0, 4.0, 13.0, 16.0, 8.0, 8.0, 6.0, 12...","['. OZ', ' OZ', '. OZ', 'OZ/CT', ' OZ', ' OZ',...",0,0,10,0,289,0,0,0,0,0,0,0,2,0,0,0,0,0,0,34,0,0,0,0,0,0,3,0,0,1,0,3,0,0,0,0,0,3,0,0,0,37,0,0
4,4,5,"[85, 85, 87, 88, 88, 88, 97, 97, 97, 97, 97, 9...","[27997276369, 27997276369, 28023500778, 280241...","[938983, 5980822, 1012352, 825538, 1002499, 69...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, ...","[1.99, 2.49, 5.54, 7.59, 2.59, 3.5, 3.34, 6.49...",374,"[0.0, 0.0, -1.85, 0.0, -0.9, -0.49, -1.85, 0.0...",1540,13,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.13, 2.66, 5.93, 8.12, 2.77, 3.75, 3.57, 6.9...","[1.99, 2.49, 7.39, 7.59, 3.49, 3.99, 5.19, 6.4...","[1.99, 2.49, 5.54, 7.59, 2.59, 3.5, 3.34, 6.49...",85,2021-03-26,"[5143, 5143, 870, 1216, 410, 5268, 69, 397, 80...","['DRUG GM', 'DRUG GM', 'DRUG GM', 'MEAT-PCKGD'...","['National', 'National', 'National', 'National...","['GREETING CARDS/WRAP/PARTY SPLY', 'GREETING C...","['CARDS SEASONAL', 'CARDS SEASONAL', 'SUNBURN ...","[' ', ' ', ' ', '4 LB', '14 OZ', '16 OZ', '32....","[nan, nan, nan, 4.0, 14.0, 16.0, 32.0, 29.0, n...","[' ', ' ', ' ', ' LB', ' OZ', ' OZ', '. OZ', '...",0,0,10,2,139,0,0,0,0,0,0,0,2,0,0,0,0,0,0,13,0,0,0,0,0,0,21,0,0,2,0,0,0,0,0,0,0,2,0,0,0,54,0,0

In [5]:
clients = hh.merge(trans_prod_per_household, on='household_key', how='inner')
clients

,marital_status_code,homeowner_desc,hh_comp_desc,household_key,age_group,adult_category_size,has_kids,avg_age,avg_income,n_kids,n_household,Unnamed: 0,day,basket_id,product_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc,sales_value_eu,loyalty_card_price,non_loyalty_card_price,days_,transaction_date,manufacturer,department,brand,commodity_desc,sub_commodity_desc,curr_size_of_product,curr_size_of_product_value,curr_size_of_product_units,COUP/STR & MFG_quantity,_quantity,MEAT_quantity,PASTRY_quantity,GROCERY_quantity,MISC SALES TRAN_quantity,POSTAL CENTER_quantity,FLORAL_quantity,RESTAURANT_quantity,PORK_quantity,SPIRITS_quantity,GRO BAKERY_quantity,COSMETICS_quantity,VIDEO RENTAL_quantity,RX_quantity,CNTRL/STORE SUP_quantity,VIDEO_quantity,DAIRY DELI_quantity,CHARITABLE CONT_quantity,MEAT-PCKGD_quantity,ELECT &PLUMBING_quantity,SEAFOOD_quantity,KIOSK-GAS_quantity,HBC_quantity,DELI/SNACK BAR_quantity,PROD-WHS SALES_quantity,DELI_quantity,AUTOMOTIVE_quantity,TOYS_quantity,NUTRITION_quantity,HOUSEWARES_quantity,SEAFOOD-PCKGD_quantity,MEAT-WHSE_quantity,GARDEN CENTER_quantity,MISC. TRANS._quantity,PHOTO_quantity,PHARMACY SUPPLY_quantity,PRODUCE_quantity,SALAD BAR_quantity,TRAVEL & LEISUR_quantity,GM MERCH EXP_quantity,DRUG GM_quantity,FROZEN GROCERY_quantity,CHEF SHOPPE_quantity
0,A,Homeowner,2 Adults No Kids,1,senior,2.0,NaN,65.0,42000,NaN,2,0,"[51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 5...","[27601281299, 27601281299, 27601281299, 276012...","[825123, 831447, 840361, 845307, 852014, 85498...","[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, ...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",436,"[0.0, 0.0, -0.3, -0.62, -1.2, -1.3, -0.49, 0.0...",1456,8,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[4.27, 3.2, 1.17, 3.97, 2.99, 7.69, 2.68, 1.59...","[3.99, 2.99, 1.39, 4.33, 3.99, 8.49, 2.99, 1.4...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",51,2021-02-20,"[1179, 317, 69, 4084, 69, 1011, 159, 407, 2082...","['GROCERY', 'GROCERY', 'GROCERY', 'DELI', 'GRO...","['National', 'National', 'Private', 'National'...","['SALD DRSNG/SNDWCH SPRD', 'CHEESE', 'EGGS', '...","['SEMI-SOLID SALAD DRESSING MAY', 'SHREDDED CH...","['30 OZ', '8 OZ', '1 DZ', ' ', '56 OZ', ' ', '...","[30.0, 8.0, 1.0, nan, 56.0, nan, 16.0, 15.0, 2...","[' OZ', ' OZ', ' DZ', ' ', ' OZ', ' ', ' OZ', ...",0,0,5,49,1310,2,0,1,3,0,0,0,0,0,0,0,0,0,0,117,0,0,0,0,0,0,68,0,0,19,0,0,0,0,0,0,0,209,13,0,0,201,0,0
1,A,Homeowner,2 Adults No Kids,7,middle-aged,2.0,NaN,49.5,62000,NaN,2,6,"[23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 2...","[27255010658, 27255010658, 27255010658, 272550...","[865569, 886703, 889731, 893400, 995436, 10205...","[2, 1, 3, 4, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, ...","[3.38, 1.09, 2.64, 4.0, 3.91, 3.86, 1.36, 2.29...",322,"[-0.2, 0.0, -2.13, -1.56, 0.0, -1.93, -0.42, -...",1435,4,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.62, 1.17, 2.82, 4.28, 4.18, 4.13, 1.46, 2.4...","[1.79, 1.09, 1.59, 1.39, 3.91, 5.79, 0.89, 2.4...","[1.69, 1.09, 0.88, 1.0, 3.91, 3.86, 0.68, 2.29...",23,2021-01-23,"[418, 69, 69, 1251, 4680, 3050, 1251, 794, 69,...","['GROCERY', 'GROCERY', 'GROCERY', 'GROCERY', '...","['National', 'Private', 'Private', 'National',...","['CONVENIENT BRKFST/WHLSM SNACKS', 'MISC. DAIR...","['GRANOLA BARS', 'REFRIGERATED MEXICAN PRODUCT...","['12 OZ', '17.5 OZ', '24 OZ', '14.75 OZ', ' ',...","[12.0, 17.0, 24.0, 14.0, nan, nan, 10.0, 12.0,...","[' OZ', '. OZ', ' OZ', '. OZ', ' ', ' ', '.OZ'...",0,0,40,9,1040,0,0,1,0,0,0,0,16,0,0,0,0,0,0,26,0,1,0,0,0,0,33,0,0,7,0,0,0,0,1,0,0,132,0,0,0,248,0,0
2,U,Unknown,2 Adults Kids,8,adult,2.0,True,29.5,29500,1.0,3,7,"[65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 6...","[27757099033, 27757099033, 27757099033, 277570...","[824550, 824555, 826578, 835576, 841220, 84798...","[1, 1, 1, 2, 3, 2, 1, 1, 1, 4, 1, 4, 1, 1, 2, ...","[3.49, 0.2, 3.99, 0.4, 11.37, 3.98, 0.88, 1.39...",321,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.11, -0.1, 0....",2149,10,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.73, 0.21, 4.27, 0.43, 12.17, 4.26, 0.94, 1....","[3.49, 0.2, 3.99, 0.2, 3.79, 1.99, 0.99, 1.49,...","[3.49, 0.2, 3.99, 0.2, 3.79, 1.99, 0.88, 1.39,...",65,2021-03-06,"[2264, 1046, 105, 1046, 2082, 1646, 69, 1768, ...","['GROCERY', 'GROCERY', 'DRUG GM', 'GROCERY', '...","['National', 'National', 'National', 'National...","['MISC. DAIRY', 'PWDR/CRYSTL DRNK MX', 'DEODOR...","['BREAD:TORTILLAS/PITA', 'SOFT DRINK POWDER PO...","['13 OZ', 'L .15 OZ', ' ', '2 QT', '12 OZ', ...","[13.0, 15.0, nan, 2.0, 12.0, 1.0, 20.0, 16.0, ...","[' OZ', 'L . OZ', ' ', ' QT', ' OZ', ' LB', ...",0,0,90,21,1693,2,0,13,0,0,5,0,6,0,0,0,0,2,0,101,0,1,65914,0,0,0,32,0,0,2,0,7,0,4,0,0,0,182,25,0,0,231,0,2
3,U,Homeowner,2 Adults Kids,13,adult,2.0,True,29.5,87000,2.0,4,12,"[101, 101, 101, 101, 104, 104, 104, 104, 104, ...","[28235291311, 28235291311, 28235291311, 282352...","[942385, 1106523, 5569230, 9883918, 840361, 84...","[1, 1, 5, 1, 1, 2, 1, 3, 1, 2, 5, 6, 2, 2, 1, ...","[12.74, 2.79, 12.5, 14.99, 1.09, 4.68, 0.86, 1...",323,"[-4.25, 0.0, -10.95, -5.0, -0.3, -1.2, -0.43, ...",1130,15,"[0.0, 0.0, -2.5, 0.0, 0.0, -0.5, 0.0, 0.0, -1....","[0.0, 0.0, 0.0, 0.0, 0.0, -0.5, 0.0, 0.0, 0.0,...","[13.63, 2.99, 13.38, 16.04, 1.17, 5.01, 0.92, ...","[16.99, 2.79, 4.69, 19.99, 1.39, 2.69, 1.29, 0...","[12.74, 2.79, 2.5, 14.99, 1.09, 2.59, 0.86, 0....",101,2021-04-11,"[6034, 69, 1208, 6034, 69, 531, 69, 693, 1136,...","['DRUG GM', 'GROCERY', 'GROCERY', 'DRUG GM', '...","['National', 'Private', 'National', 'National'...","['SPRING/SUMMER SEASONAL', 'FLUID MILK PRODUCT...","['INFLATABLES', 'FLUID MILK WHITE ONLY', 'SOFT...","[' ', '1 GA', '12 OZ', '48INCH', '1 DZ', '33.8...","[nan, 1.0, 12.0, 48.0, 1.0, 33.0, 12.0, 1.0, 1...","[' ', ' GA', ' OZ', 'INCH', ' DZ', '. OZ', ' C...",0,0,1,5,2342,461116,0,4,0,0,0,0,8,0,0,0,0,0,0,124,0,0,1399474,0,0,0,31,1,0,2,0,6,0,0,0,0,0,116,3,0,0,596,0,0
4,B,Homeowner,Single Female,16,middle-aged,1.0,False,49.5,62000,NaN,1,15,"[98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 9...","[28171905027, 28171905027, 28171905027, 281719...","[2378842, 2427281, 2625067, 7029671, 2403771, ...","[1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, ...","[1.69, 2.89, 3.49, 2.39, 1.98, 0.79, 5.98, 4.9...",3316,"[0.0, 0.0, 0.0, 0.0, -0.35, 0.0, 0.0, 0.0, 0.0...",657,15,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.81, 3.09, 3.73, 2.56, 2.12, 0.85, 6.4, 5.33...","[1.69, 2.89, 3.49, 2.39, 2.33, 0.79, 2.99, 2.4...","[1.69, 2.89, 3.49, 2.39, 1.98, 0.79, 2.99, 2.4...",98,2021-04-08,"[1804, 194, 1089, 136, 3177, 69, 75, 194, 4841...","['GROCERY', 'GROCERY', 'MEAT-PCKGD', 'GROCERY'...","['National', 'National', 'National', 'National...","['BAKED BREAD/BUNS/ROLLS', 'COLD CEREAL', 'DIN...","['HOT DOG BUNS', 'KIDS CEREAL', 'RED', 'DOG BI...","['11 OZ', '12 OZ', '16 OZ', '14 OZ', ' ', '1 P...","[11.0, 12.0, 16.0, 14.0, nan, 1.0, 28.0, 7.0, ...","[' OZ', ' OZ', ' OZ', ' OZ', ' ', ' PT', ' OZ'...",0,0,16,26,383,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19,0,0,80628,0,0,0,28,0,0,4,0,0,0,0,0,0,0,44,2,0,0,50,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,U,Homeowner,2 Adults No Kids,2494,middle-aged,2.0,NaN,39.5,62000,NaN,2,2493,"[114, 114, 114, 114, 114, 114, 114, 114, 114, ...","[28345214231, 28345214231, 28345214231, 283452...","[825550, 825650, 849843, 860348, 861272, 87061...","[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, ...","[1.59, 0.89, 0.99, 6.99, 0.69, 7.79, 4.85, 3.4...",333,"[0.0, -0.5, 0.0, 0.0, 0.0, -0.2, 0.0, 0.0, -0....",2047,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.7, 0.95, 1.06, 7.48, 0.74, 8.34, 5.19, 3.73...","[1.59, 1.39, 0.99, 6.99, 0.69, 7.99, 4.85, 3.4...","[1.59, 0.89, 0.99, 6.99, 0.69, 7.79, 4.85, 3.4...",114,2021-04-24,"[407, 69, 69, 2496, 69, 764, 3035, 883, 693, 1...","['GROCERY', 'GROCERY', 'GROCERY', 'GROCERY', '...","['National', 'Private', 'Private', 'National',...","['DRY MIX DESSERTS', 'DRY MIX DESSERTS', 'BAKE...","['PUDDING&GELATIN CUPS/CANS', 'PUDDING&GELATIN...","['14.0 OZ', '14.0 OZ', '20 OZ', '1.5 LTR', '6 ...","[14.0, 14.0, 20.0, 1.0, 6.0, 32.0, nan, 1.0, 1...","['. OZ', '. OZ', ' OZ', '. LTR', ' CT', ' LOAD...",0,0,19,23,513,0,0,2,0,0,1,0,3,0,0,0,0,0,0,36,0,1,57070,0,0,0,17,1,0,1,0,7,0,0,0,0,0,114,0,0,0,67,0,0
797,A,Homeowner,Unknown,2496,middle-aged,NaN,NaN,49.5,87000,1.0,3,2495,"[117, 117, 117, 117, 117, 117, 117, 117, 117, ...","[28391736778, 28391736778, 28391736778, 283917...","[840361, 852159, 871756, 886703, 899624, 91612...","[1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 6, 1, 1, 1, ...","[0.79, 3.71, 2.95, 1.09, 2.99, 5.32, 16.24, 1....",370,"[-0.6, 0.0, -0.74, 0.0, 0.0, -7.47, 0.0, -0.3,...",1345,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.85, 3.97, 3.16, 1.17, 3.2, 5.69, 17.38, 1.8...","[1.39, 3.71, 3.69, 1.09, 2.99, 6.4, 16.24, 1.9...","[0.79, 3.71, 2.95, 1.09, 2.99, 2.66, 16.24, 1....",117,2021-04-27,"[69, 2946, 317, 69, 69, 4314, 2908, 69, 1276, ...","['GROCERY', 'MEAT', 'GROCERY', 'GROCERY', 'PRO...","['Private', 'National', 'National', 'Private',...","['EGGS', 'BEEF', 'SALD DRSNG/SNDWCH SPRD', 'MI...","['EGGS - LARGE', 'CHOICE BEEF', 'SEMI-SOLID SA...","['1 DZ', ' ', '32 OZ', '17.5 OZ', '10 LB', ' '...","[1.0, nan, 32.0, 17.0, 10.0, nan, nan, 16.0, 1...","[' DZ', ' ', ' OZ', '. OZ', ' LB', ' ', ' ', '...",0,0,246,27,1124,12,2,0,0,0,1,0,0,0,0,0,0,0,0,91,0,12,128411,0,0,0,37,0,0,6,0,2,0,0,0,0,0,159,0,0,0,173,1,0
798,U,Unknown,Single Male,2497,middle-aged,1.0,False,49.5,42000,NaN,1,2496,"[78, 78, 78, 78, 78, 80, 80, 80, 80, 80, 82, 8...","[27913035576, 27913035576, 27913035576, 279130...","[838220, 1037840, 1052294, 5569230, 8090537, 1...","[1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, ...","[25.33, 3.04, 29.34, 5.0, 3.34, 7.99, 5.0, 5.0...",339,"[0.0, 0.0, 0.0, -4.38, -1.25, 0.0, -4.38, -4.3...",1121,12,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[27.1, 3.25, 31.39, 5.35, 3.57, 8.55, 5.35, 5....","[25.33, 3.04, 29.34, 4.69, 4.59, 7.99, 4.69, 4...","[25.33, 3.04, 29.34, 2.5, 3.34, 7.99, 2.5, 2.5...",78,2021-03-19,"[539, 539, 539, 1208, 103, 2, 1208, 1208, 1208...","['DRUG GM', 'DRUG GM', 'DRUG GM', 'GROCERY', '...","['National', 'National', 'National', 'National...","['CIGARETTES', 'CIGARETTES', 'CIGARETTES', 'SO...","['CIGARETTES', 'CIGARETTES', 'CIGARETTES', 'SO...","['525345 CTN', '973875 PK', '522946 CTN', '12...","[525345.0, 973875.0, 522946.0, 12.0, 12.0, 12....","[' CTN', ' PK', ' CTN', ' OZ', ' OZ', ' OZ', ...",0,0,94,16,2062,3,0,4,0,0,0,0,5,0,0,0,0,0,0,94,0,0,58262,0,0,0,59,0,0,2,0,9,0,0,0,0,0,445,2,0,0,179,0,0
799,U,Homeowner,2 Adults No Kids,2498,adult,2.0,NaN,29.5,62000,NaN,2,2497,"[105, 105, 105, 105, 105, 105, 105, 105, 105, ...","[28243481507, 28243481507, 28243481507, 282434...","[824555, 835576, 901776, 904023, 911215, 91749...","[1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, ...","[0.1, 0.1, 2.69, 0.1, 0.1, 0.1, 0.1, 0.2, 0.1,...",309,"[-0.1, -0.1, -1.3, -0.1, -0.1, -0.1, -0.1, -0....",1823,16,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.11, 0.11, 2.88, 0.11, 0.11, 0.11, 0.11, 0.2...","[0.2, 0.2, 3.99, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,...","[0.1, 0.1, 2.69, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...",105,2021-04-15,"[1046, 1046, 436, 1046, 1046, 1046, 1046, 1046...","['GROCERY', 'GROCERY', 'GROCERY', 'GROCERY', '...","['National', 'National', 'National', 'National...","['PWDR/CRYSTL DRNK MX', 'PWDR/CRYSTL DRNK MX',...","['SOFT DRINK POWDER POUCHES', 'SOFT DRINK POWD...","['L .15 OZ', '2 QT', '59 OZ', '2 QT', '.13 O...","[15.0, 2.0, 59.0, 2.0, 13.0, 17.0, 2.0, 14.0, ...","['L . OZ', ' QT', ' OZ', ' QT', '. OZ', '. O...",0,0,6,19,703,30384,0,1,0,0,2,0,1,0,0,0,0,0,0,40,0,0,0,0,0,0,10,0,0,20,0,0,0,0,0,0,0,55,5,1,0,92,0,0
800,U,Unknown,2 Adults Kids,2499,adult,2.0,True,29.5,15000,1.0,3,2498,"[70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 85, 8...","[27816885334, 27816885334, 27816885334, 278168...","[838186, 853197, 864143, 883665, 932949, 93383...","[1, 1, 6, 7, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, ...","[3.99, 1.5, 4.74, 19.53, 2.38, 4.9, 3.34, 3.35...",31782,"[0.0, -0.39, -0.6, -3.5, 0.0, -0.98, -0.65, 0....",1056,11,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[4.27, 1.61, 5.07, 20.9, 2.55, 5.24, 3.57, 3.5...","[3.99, 1.89, 0.89, 3.29, 2.38, 2.94, 3.99, 3.3...","[3.99, 1.5, 0.79, 2.79, 2.38, 2.45, 3.34, 3.35...",70,2021-03-11,"[1790, 1914, 69, 1046, 3869, 3705, 103, 3787, ...","['GROCERY', 'GROCERY', 'GROCERY', 'GROCERY', '...","['National', 'National', 'Private', 'National'...","['BAKED SWEET GOODS', 'BAKED BREAD/BUNS/ROLLS'...","['SW GDS:DONUTS', 'RYE BREADS', 'FLUID MILK WH...","['18.2 OZ', '16 OZ', '1 PT', '6 PK', ' ', ' ',...","[18.0, 16.0, 1.0, 6.0, nan, nan, 24.0, nan, 20...","['. OZ', ' OZ', ' PT', ' PK', ' ', ' ', ' OZ',...",0,0,34,29,1228,70771,0,5,0,0,0,0,0,0,0,0,0,0,0,71,0,0,71137,0,0,0,8,0,0,4,0,0,0,0,1,0,0,57,0,2,0,102,0,0

In [6]:
columns_to_drop = [
    'Unnamed: 0', 'day', 'basket_id', 'product_id', 'sales_value',
    'store_id', 'retail_disc', 'trans_time', 'week_no', 'coupon_disc',
    'coupon_match_disc', 'loyalty_card_price',
    'non_loyalty_card_price', 'days_', 'transaction_date', 'manufacturer',
    'brand', 'commodity_desc', 'sub_commodity_desc',
    'curr_size_of_product', 'curr_size_of_product_value',
    'curr_size_of_product_units'
]

# Drop the specified columns from the DataFrame `clients`
clients_cleaned = clients.drop(columns=columns_to_drop)
clients_cleaned

,marital_status_code,homeowner_desc,hh_comp_desc,household_key,age_group,adult_category_size,has_kids,avg_age,avg_income,n_kids,n_household,quantity,sales_value_eu,department,COUP/STR & MFG_quantity,_quantity,MEAT_quantity,PASTRY_quantity,GROCERY_quantity,MISC SALES TRAN_quantity,POSTAL CENTER_quantity,FLORAL_quantity,RESTAURANT_quantity,PORK_quantity,SPIRITS_quantity,GRO BAKERY_quantity,COSMETICS_quantity,VIDEO RENTAL_quantity,RX_quantity,CNTRL/STORE SUP_quantity,VIDEO_quantity,DAIRY DELI_quantity,CHARITABLE CONT_quantity,MEAT-PCKGD_quantity,ELECT &PLUMBING_quantity,SEAFOOD_quantity,KIOSK-GAS_quantity,HBC_quantity,DELI/SNACK BAR_quantity,PROD-WHS SALES_quantity,DELI_quantity,AUTOMOTIVE_quantity,TOYS_quantity,NUTRITION_quantity,HOUSEWARES_quantity,SEAFOOD-PCKGD_quantity,MEAT-WHSE_quantity,GARDEN CENTER_quantity,MISC. TRANS._quantity,PHOTO_quantity,PHARMACY SUPPLY_quantity,PRODUCE_quantity,SALAD BAR_quantity,TRAVEL & LEISUR_quantity,GM MERCH EXP_quantity,DRUG GM_quantity,FROZEN GROCERY_quantity,CHEF SHOPPE_quantity
0,A,Homeowner,2 Adults No Kids,1,senior,2.0,NaN,65.0,42000,NaN,2,"[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, ...","[4.27, 3.2, 1.17, 3.97, 2.99, 7.69, 2.68, 1.59...","['GROCERY', 'GROCERY', 'GROCERY', 'DELI', 'GRO...",0,0,5,49,1310,2,0,1,3,0,0,0,0,0,0,0,0,0,0,117,0,0,0,0,0,0,68,0,0,19,0,0,0,0,0,0,0,209,13,0,0,201,0,0
1,A,Homeowner,2 Adults No Kids,7,middle-aged,2.0,NaN,49.5,62000,NaN,2,"[2, 1, 3, 4, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, ...","[3.62, 1.17, 2.82, 4.28, 4.18, 4.13, 1.46, 2.4...","['GROCERY', 'GROCERY', 'GROCERY', 'GROCERY', '...",0,0,40,9,1040,0,0,1,0,0,0,0,16,0,0,0,0,0,0,26,0,1,0,0,0,0,33,0,0,7,0,0,0,0,1,0,0,132,0,0,0,248,0,0
2,U,Unknown,2 Adults Kids,8,adult,2.0,True,29.5,29500,1.0,3,"[1, 1, 1, 2, 3, 2, 1, 1, 1, 4, 1, 4, 1, 1, 2, ...","[3.73, 0.21, 4.27, 0.43, 12.17, 4.26, 0.94, 1....","['GROCERY', 'GROCERY', 'DRUG GM', 'GROCERY', '...",0,0,90,21,1693,2,0,13,0,0,5,0,6,0,0,0,0,2,0,101,0,1,65914,0,0,0,32,0,0,2,0,7,0,4,0,0,0,182,25,0,0,231,0,2
3,U,Homeowner,2 Adults Kids,13,adult,2.0,True,29.5,87000,2.0,4,"[1, 1, 5, 1, 1, 2, 1, 3, 1, 2, 5, 6, 2, 2, 1, ...","[13.63, 2.99, 13.38, 16.04, 1.17, 5.01, 0.92, ...","['DRUG GM', 'GROCERY', 'GROCERY', 'DRUG GM', '...",0,0,1,5,2342,461116,0,4,0,0,0,0,8,0,0,0,0,0,0,124,0,0,1399474,0,0,0,31,1,0,2,0,6,0,0,0,0,0,116,3,0,0,596,0,0
4,B,Homeowner,Single Female,16,middle-aged,1.0,False,49.5,62000,NaN,1,"[1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, ...","[1.81, 3.09, 3.73, 2.56, 2.12, 0.85, 6.4, 5.33...","['GROCERY', 'GROCERY', 'MEAT-PCKGD', 'GROCERY'...",0,0,16,26,383,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19,0,0,80628,0,0,0,28,0,0,4,0,0,0,0,0,0,0,44,2,0,0,50,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,U,Homeowner,2 Adults No Kids,2494,middle-aged,2.0,NaN,39.5,62000,NaN,2,"[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, ...","[1.7, 0.95, 1.06, 7.48, 0.74, 8.34, 5.19, 3.73...","['GROCERY', 'GROCERY', 'GROCERY', 'GROCERY', '...",0,0,19,23,513,0,0,2,0,0,1,0,3,0,0,0,0,0,0,36,0,1,57070,0,0,0,17,1,0,1,0,7,0,0,0,0,0,114,0,0,0,67,0,0
797,A,Homeowner,Unknown,2496,middle-aged,NaN,NaN,49.5,87000,1.0,3,"[1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 6, 1, 1, 1, ...","[0.85, 3.97, 3.16, 1.17, 3.2, 5.69, 17.38, 1.8...","['GROCERY', 'MEAT', 'GROCERY', 'GROCERY', 'PRO...",0,0,246,27,1124,12,2,0,0,0,1,0,0,0,0,0,0,0,0,91,0,12,128411,0,0,0,37,0,0,6,0,2,0,0,0,0,0,159,0,0,0,173,1,0
798,U,Unknown,Single Male,2497,middle-aged,1.0,False,49.5,42000,NaN,1,"[1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, ...","[27.1, 3.25, 31.39, 5.35, 3.57, 8.55, 5.35, 5....","['DRUG GM', 'DRUG GM', 'DRUG GM', 'GROCERY', '...",0,0,94,16,2062,3,0,4,0,0,0,0,5,0,0,0,0,0,0,94,0,0,58262,0,0,0,59,0,0,2,0,9,0,0,0,0,0,445,2,0,0,179,0,0
799,U,Homeowner,2 Adults No Kids,2498,adult,2.0,NaN,29.5,62000,NaN,2,"[1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, ...","[0.11, 0.11, 2.88, 0.11, 0.11, 0.11, 0.11, 0.2...","['GROCERY', 'GROCERY', 'GROCERY', 'GROCERY', '...",0,0,6,19,703,30384,0,1,0,0,2,0,1,0,0,0,0,0,0,40,0,0,0,0,0,0,10,0,0,20,0,0,0,0,0,0,0,55,5,1,0,92,0,0
800,U,Unknown,2 Adults Kids,2499,adult,2.0,True,29.5,15000,1.0,3,"[1, 1, 6, 7, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, ...","[4.27, 1.61, 5.07, 20.9, 2.55, 5.24, 3.57, 3.5...","['GROCERY', 'GROCERY', 'GROCERY', 'GROCERY', '...",0,0,34,29,1228,70771,0,5,0,0,0,0,0,0,0,0,0,0,0,71,0,0,71137,0,0,0,8,0,0,4,0,0,0,0,1,0,0,57,0,2,0,102,0,0

In [7]:
for index, row in clients_cleaned.iterrows():
    a = row['household_key']
    print(a)

1
7
8
13
16
17
18
19
20
22
25
27
31
39
40
42
43
46
48
49
52
55
56
57
58
67
71
74
77
78
80
85
86
97
98
101
104
105
109
110
113
114
117
118
119
121
123
127
131
133
134
136
139
149
155
157
158
159
161
164
165
166
170
178
184
192
193
198
201
208
209
211
212
214
216
218
219
220
221
222
230
232
235
239
242
243
248
249
250
253
256
257
263
264
276
281
282
283
289
290
294
300
301
302
304
306
309
314
317
319
321
324
325
329
332
334
346
350
351
353
354
358
361
362
367
370
371
377
378
381
383
385
386
387
389
390
391
392
395
400
404
409
410
411
412
413
417
418
426
428
432
434
437
438
441
442
443
451
454
456
458
460
462
464
469
473
483
484
485
489
490
491
492
493
510
513
518
523
526
527
534
540
542
543
546
548
553
560
567
569
574
575
576
578
582
583
586
588
593
595
596
597
598
601
605
606
607
608
609
614
621
622
623
624
630
631
644
647
660
661
670
671
672
675
680
682
685
688
690
692
693
695
696
699
706
707
708
712
714
715
716
718
722
725
731
732
733
740
741
742
748
752
753
755
761
762
764
766
768
770
771
779
784
785
786
787
788
790
797
800
802
803
806
808
816
817
823
825
831
840
844
845
852
853
856
857
859
863
864
865
866
867
868
871
875
878
879
882
883
886
888
889
895
898
900
903
906
908
911
914
915
920
922
926
929
932
934
939
941
946
947
949
955
956
960
968
971
973
976
979
981
982
983
986
992
993
996
997
1001
1003
1004
1012
1014
1015
1018
1020
1021
1024
1031
1038
1040
1041
1042
1045
1053
1057
1060
1062
1066
1069
1070
1074
1076
1081
1082
1084
1091
1094
1103
1113
1120
1123
1128
1130
1131
1135
1137
1138
1142
1146
1147
1151
1154
1158
1159
1160
1163
1164
1166
1167
1169
1172
1174
1175
1178
1179
1186
1188
1190
1197
1218
1219
1222
1226
1228
1229
1234
1236
1240
1247
1248
1256
1257
1258
1260
1261
1263
1264
1267
1268
1270
1272
1285
1291
1296
1297
1299
1300
1305
1306
1316
1318
1321
1326
1333
1337
1352
1354
1357
1363
1364
1367
1369
1370
1376
1378
1382
1388
1389
1391
1393
1394
1396
1397
1402
1412
1418
1419
1421
1423
1425
1428
1429
1430
1437
1438
1443
1445
1451
1452
1453
1454
1461
1462
1467
1468
1470
1474
1475
1479
1481
1483
1484
1485
1488
1491
1492
1494
1499
1505
1509
1517
1524
1527
1528
1529
1534
1536
1537
1540
1541
1545
1549
1556
1557
1563
1566
1567
1568
1572
1578
1580
1585
1588
1591
1595
1604
1609
1618
1627
1631
1633
1634
1648
1649
1650
1653
1662
1676
1677
1678
1680
1686
1689
1692
1693
1694
1695
1696
1707
1708
1709
1710
1720
1722
1726
1740
1745
1748
1749
1751
1753
1759
1762
1764
1765
1775
1778
1779
1785
1788
1791
1795
1796
1797
1800
1802
1803
1804
1812
1814
1815
1816
1820
1822
1823
1829
1831
1833
1834
1841
1844
1845
1847
1848
1850
1858
1861
1864
1865
1869
1873
1879
1892
1894
1896
1899
1901
1907
1911
1914
1917
1919
1920
1921
1923
1926
1927
1928
1929
1931
1935
1937
1939
1944
1946
1948
1949
1953
1955
1962
1964
1965
1975
1976
1979
1980
1982
1985
1989
1990
1995
1997
2002
2004
2006
2007
2011
2012
2013
2017
2018
2020
2023
2024
2030
2040
2041
2050
2053
2057
2058
2062
2063
2064
2068
2069
2070
2076
2082
2084
2085
2086
2087
2088
2092
2094
2097
2100
2102
2107
2110
2111
2112
2115
2116
2119
2121
2123
2124
2129
2130
2133
2134
2140
2147
2148
2154
2156
2158
2162
2168
2172
2173
2179
2181
2182
2183
2184
2185
2186
2188
2190
2193
2194
2198
2199
2200
2203
2208
2209
2217
2221
2224
2231
2233
2234
2235
2237
2243
2250
2252
2254
2260
2264
2266
2269
2272
2279
2280
2282
2284
2292
2294
2295
2296
2298
2300
2302
2305
2307
2312
2314
2317
2318
2322
2324
2328
2330
2331
2334
2337
2341
2342
2343
2347
2351
2359
2360
2361
2364
2367
2370
2374
2376
2378
2380
2390
2393
2397
2400
2405
2406
2407
2411
2420
2421
2426
2427
2432
2435
2437
2445
2446
2447
2448
2449
2453
2455
2465
2467
2479
2483
2486
2488
2489
2494
2496
2497
2498
2499

In [10]:
import pandas as pd
import ast

# Sample data loading (replace with actual data)
# clients_cleaned = pd.read_csv('your_file.csv')

# Convert string representations of lists to actual lists if needed
clients_cleaned['department'] = clients_cleaned['department'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
clients_cleaned['sales_value_eu'] = clients_cleaned['sales_value_eu'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
clients_cleaned['quantity'] = clients_cleaned['quantity'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Convert lists within DataFrame columns to numeric values if necessary
clients_cleaned['sales_value_eu'] = clients_cleaned['sales_value_eu'].apply(lambda x: list(map(float, x)))
clients_cleaned['quantity'] = clients_cleaned['quantity'].apply(lambda x: list(map(float, x)))

# Initialize an empty list to collect rows
rows = []

# Iterate over each row in the DataFrame
for index, row in clients_cleaned.iterrows():
    household_key = row['household_key']
    departments = row['department']  # Ensure this is a list of department names
    sales_values = row['sales_value_eu']  # Ensure this is a list of sales values (numeric)
    quantities = row['quantity']  # Ensure this is a list of quantities (numeric)

    # Create a dictionary to store the total spending for each department
    total_spending = {}
    
    for dept, sales_value, quantity in zip(departments, sales_values, quantities):
        if dept not in total_spending:
            total_spending[dept] = 0
        total_spending[dept] += sales_value * quantity
    
    # Convert the dictionary to a DataFrame row
    spending_row = {'household_key': household_key}
    spending_row.update(total_spending)
    
    # Append the row to the list
    rows.append(spending_row)

# Convert the list of rows into a DataFrame
spending_per_department = pd.DataFrame(rows)

# Fill NaN values with 0 (for departments with no spending)
spending_per_department.fillna(0, inplace=True)

# Display the result
spending_per_department.head()

,household_key,GROCERY,DELI,MEAT-PCKGD,PASTRY,PRODUCE,DRUG GM,,MEAT,SALAD BAR,NUTRITION,MISC SALES TRAN,RESTAURANT,FLORAL,COSMETICS,MISC. TRANS.,SEAFOOD,KIOSK-GAS,SPIRITS,CHEF SHOPPE,SEAFOOD-PCKGD,GARDEN CENTER,DAIRY DELI,AUTOMOTIVE,CNTRL/STORE SUP,COUP/STR & MFG,TRAVEL & LEISUR,GM MERCH EXP,POSTAL CENTER,FROZEN GROCERY,DELI/SNACK BAR,VIDEO,RX,PROD-WHS SALES,MEAT-WHSE,PHOTO,PHARMACY SUPPLY,TOYS,GRO BAKERY,HOUSEWARES,HBC,VIDEO RENTAL
0,1,3672.10,226.99,394.15,127.38,434.72,712.80,0.0,23.92,67.59,51.74,21.40,4.47,8.55,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7,2595.66,171.57,85.07,27.62,339.31,845.93,0.0,229.72,0.00,22.08,0.00,0.00,5.34,101.34,1.87,7.05,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,8,4332.98,152.36,436.25,112.60,438.86,1182.17,0.0,606.87,77.71,12.82,3.38,0.00,225.63,36.14,0.00,2.00,1723743.25,53.45,5.36,40.80,57.08,2.14,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,13,9314.94,104.85,533.57,15.52,341.16,4782.13,0.0,20.47,10.80,3.54,30899529.93,0.00,50.24,51.38,0.00,0.00,63359349.72,0.00,0.00,25.53,0.00,0.00,7.69,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,16,1025.94,104.74,62.94,88.25,93.57,94.35,0.0,120.13,6.88,9.47,0.00,0.00,0.00,0.00,0.00,0.00,2083362.13,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
a = clients_cleaned[clients_cleaned['household_key'] == 13]
pd.set_option('display.max_colwidth', None)
a[['quantity', 'department', 'sales_value_eu']]

,quantity,department,sales_value_eu
3,"[1.0, 1.0, 5.0, 1.0, 1.0, 2.0, 1.0, 3.0, 1.0, 2.0, 5.0, 6.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 0.0, 1.0, 1.0, 1.0, 2.0, 2.0, 3.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0, 4.0, 1.0, 3.0, 0.0, 1.0, 1.0, 2.0, 24933.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 3.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 15617.0, 1.0, 1.0, 1.0, 4.0, 1.0, 2.0, ...]","[DRUG GM, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, GROCERY, GROCERY, MEAT-PCKGD, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, MEAT-PCKGD, GROCERY, , GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, DRUG GM, MEAT-PCKGD, DRUG GM, GROCERY, GROCERY, DRUG GM, DRUG GM, DRUG GM, PRODUCE, DRUG GM, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, , GROCERY, MEAT-PCKGD, DRUG GM, MISC SALES TRAN, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, PRODUCE, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, GROCERY, DRUG GM, GROCERY, DRUG GM, DRUG GM, GROCERY, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, KIOSK-GAS, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, ...]","[13.63, 2.99, 13.38, 16.04, 1.17, 5.01, 0.92, 1.07, 3.41, 7.36, 4.23, 8.66, 3.52, 2.14, 1.12, 3.41, 3.84, 4.27, 2.14, 2.13, 3.83, 1.79, 0.75, 2.99, 2.77, 1.07, 4.27, 0.0, 5.34, 4.27, 1.61, 3.21, 2.12, 3.21, 17.1, 6.56, 0.86, 1.69, 2.14, 0.43, 0.86, 0.86, 2.13, 3.52, 2.14, 4.26, 4.28, 1.61, 3.21, 0.0, 1.79, 3.2, 17.1, 63.73, 3.31, 4.79, 0.86, 0.86, 1.28, 0.86, 0.86, 1.28, 0.86, 0.86, 2.96, 1.28, 0.86, 1.28, 0.86, 15.84, 0.86, 0.86, 1.28, 0.86, 0.86, 0.86, 0.86, 0.86, 1.28, 0.86, 0.86, 0.86, 2.99, 0.86, 2.77, 2.02, 1.28, 6.41, 4.06, 4.28, 23.53, 16.03, 2.14, 36.92, 2.11, 1.79, 2.13, 1.71, 1.79, 7.49, ...]"

In [22]:
def contains_specific_quantity(row, quantity_value):
    return quantity_value in row


filtered_a = a[a['quantity'].apply(lambda x: contains_specific_quantity(x, 24933.0))]
filtered_a

,marital_status_code,homeowner_desc,hh_comp_desc,household_key,age_group,adult_category_size,has_kids,avg_age,avg_income,n_kids,n_household,quantity,sales_value_eu,department,COUP/STR & MFG_quantity,_quantity,MEAT_quantity,PASTRY_quantity,GROCERY_quantity,MISC SALES TRAN_quantity,POSTAL CENTER_quantity,FLORAL_quantity,RESTAURANT_quantity,PORK_quantity,SPIRITS_quantity,GRO BAKERY_quantity,COSMETICS_quantity,VIDEO RENTAL_quantity,RX_quantity,CNTRL/STORE SUP_quantity,VIDEO_quantity,DAIRY DELI_quantity,CHARITABLE CONT_quantity,MEAT-PCKGD_quantity,ELECT &PLUMBING_quantity,SEAFOOD_quantity,KIOSK-GAS_quantity,HBC_quantity,DELI/SNACK BAR_quantity,PROD-WHS SALES_quantity,DELI_quantity,AUTOMOTIVE_quantity,TOYS_quantity,NUTRITION_quantity,HOUSEWARES_quantity,SEAFOOD-PCKGD_quantity,MEAT-WHSE_quantity,GARDEN CENTER_quantity,MISC. TRANS._quantity,PHOTO_quantity,PHARMACY SUPPLY_quantity,PRODUCE_quantity,SALAD BAR_quantity,TRAVEL & LEISUR_quantity,GM MERCH EXP_quantity,DRUG GM_quantity,FROZEN GROCERY_quantity,CHEF SHOPPE_quantity
3,U,Homeowner,2 Adults Kids,13,adult,2.0,True,29.5,87000,2.0,4,"[1.0, 1.0, 5.0, 1.0, 1.0, 2.0, 1.0, 3.0, 1.0, 2.0, 5.0, 6.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 0.0, 1.0, 1.0, 1.0, 2.0, 2.0, 3.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0, 4.0, 1.0, 3.0, 0.0, 1.0, 1.0, 2.0, 24933.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 3.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 15617.0, 1.0, 1.0, 1.0, 4.0, 1.0, 2.0, ...]","[13.63, 2.99, 13.38, 16.04, 1.17, 5.01, 0.92, 1.07, 3.41, 7.36, 4.23, 8.66, 3.52, 2.14, 1.12, 3.41, 3.84, 4.27, 2.14, 2.13, 3.83, 1.79, 0.75, 2.99, 2.77, 1.07, 4.27, 0.0, 5.34, 4.27, 1.61, 3.21, 2.12, 3.21, 17.1, 6.56, 0.86, 1.69, 2.14, 0.43, 0.86, 0.86, 2.13, 3.52, 2.14, 4.26, 4.28, 1.61, 3.21, 0.0, 1.79, 3.2, 17.1, 63.73, 3.31, 4.79, 0.86, 0.86, 1.28, 0.86, 0.86, 1.28, 0.86, 0.86, 2.96, 1.28, 0.86, 1.28, 0.86, 15.84, 0.86, 0.86, 1.28, 0.86, 0.86, 0.86, 0.86, 0.86, 1.28, 0.86, 0.86, 0.86, 2.99, 0.86, 2.77, 2.02, 1.28, 6.41, 4.06, 4.28, 23.53, 16.03, 2.14, 36.92, 2.11, 1.79, 2.13, 1.71, 1.79, 7.49, ...]","[DRUG GM, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, GROCERY, GROCERY, MEAT-PCKGD, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, MEAT-PCKGD, GROCERY, , GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, DRUG GM, MEAT-PCKGD, DRUG GM, GROCERY, GROCERY, DRUG GM, DRUG GM, DRUG GM, PRODUCE, DRUG GM, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, , GROCERY, MEAT-PCKGD, DRUG GM, MISC SALES TRAN, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, PRODUCE, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, DRUG GM, GROCERY, DRUG GM, GROCERY, DRUG GM, DRUG GM, GROCERY, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, KIOSK-GAS, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, ...]",0,0,1,5,2342,461116,0,4,0,0,0,0,8,0,0,0,0,0,0,124,0,0,1399474,0,0,0,31,1,0,2,0,6,0,0,0,0,0,116,3,0,0,596,0,0