In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
transaction = pd.read_csv("C:/Users/aprataso/Downloads/final_data/trans.csv")
prod = pd.read_csv("C:/Users/aprataso/Downloads/final_data/prod.csv")

In [4]:
merger = transaction.merge(prod, on = 'product_id', how = 'left')

In [5]:
merger

,household_key,basket_id,day,product_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc,sales_value_eu,loyalty_card_price,non_loyalty_card_price,days_,transaction_date,manufacturer,department,brand,commodity_desc,sub_commodity_desc,curr_size_of_product,curr_size_of_product_value,curr_size_of_product_units
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,0.0,0.0,1.49,1.99,1.39,1,2021-01-01,69,PRODUCE,Private,POTATOES,POTATOES RUSSET (BULK&BAG),5 LB,5.0,LB
1,2375,26984851472,1,1033142,1,0.82,364,0.00,1631,1,0.0,0.0,0.88,0.82,0.82,1,2021-01-01,2,PRODUCE,National,ONIONS,ONIONS SWEET (BULK&BAG),40 LB,40.0,LB
2,2375,26984851472,1,1036325,1,0.99,364,-0.30,1631,1,0.0,0.0,1.06,1.29,0.99,1,2021-01-01,69,PRODUCE,Private,VEGETABLES - ALL OTHERS,CELERY,,NaN,
3,2375,26984851472,1,1082185,1,1.21,364,0.00,1631,1,0.0,0.0,1.29,1.21,1.21,1,2021-01-01,2,PRODUCE,National,TROPICAL FRUIT,BANANAS,40 LB,40.0,LB
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,0.0,0.0,1.61,1.89,1.50,1,2021-01-01,69,PRODUCE,Private,ORGANICS FRUIT & VEGETABLES,ORGANIC CARROTS,1 LB,1.0,LB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2595727,1598,42305362535,711,92130,1,0.99,3228,0.00,1520,102,0.0,0.0,1.06,0.99,0.99,711,2022-12-12,560,GROCERY,National,MARGARINES,MARGARINE: TUBS AND BOWLS,16 OZ,16.0,OZ
2595728,1598,42305362535,711,114102,1,8.89,3228,0.00,1520,102,0.0,0.0,9.51,8.89,8.89,711,2022-12-12,2398,GROCERY,National,BEERS/ALES,BEERALEMALT LIQUORS,12 OZ,12.0,OZ
2595729,1598,42305362535,711,133449,1,6.99,3228,0.00,1520,102,0.0,0.0,7.48,6.99,6.99,711,2022-12-12,2468,GROCERY,National,BEERS/ALES,BEERALEMALT LIQUORS,12 OZ,12.0,OZ
2595730,1598,42305362535,711,6923644,1,4.50,3228,-0.49,1520,102,0.0,0.0,4.82,4.99,4.50,711,2022-12-12,2390,GROCERY,National,BEERS/ALES,BEERALEMALT LIQUORS,4PK/10 OZ,4.0,PK/ OZ
2595731,1598,42305362535,711,14055192,1,6.99,3228,0.00,1520,102,0.0,0.0,7.48,6.99,6.99,711,2022-12-12,2536,GROCERY,National,MISC WINE,BEERALEMALT LIQUORS,6PK/11.2OZ,6.0,PK/.OZ

reducing departments (depricated)

In [6]:
print(merger['department'].unique())

['PRODUCE' 'GROCERY' 'DRUG GM' 'MEAT' 'MEAT-PCKGD' 'DELI' 'SEAFOOD-PCKGD'
 ' ' 'PASTRY' 'NUTRITION' 'VIDEO RENTAL' 'MISC SALES TRAN' 'FLORAL'
 'SEAFOOD' 'SALAD BAR' 'AUTOMOTIVE' 'SPIRITS' 'COSMETICS' 'MISC. TRANS.'
 'GARDEN CENTER' 'CHEF SHOPPE' 'TRAVEL & LEISUR' 'COUP/STR & MFG'
 'KIOSK-GAS' 'FROZEN GROCERY' 'RESTAURANT' 'HOUSEWARES' 'PORK'
 'POSTAL CENTER' 'GM MERCH EXP' 'CNTRL/STORE SUP' 'PROD-WHS SALES'
 'DAIRY DELI' 'HBC' 'CHARITABLE CONT' 'RX' 'DELI/SNACK BAR'
 'PHARMACY SUPPLY' 'PHOTO' 'ELECT &PLUMBING' 'MEAT-WHSE' 'TOYS'
 'GRO BAKERY' 'VIDEO']

In [7]:
agg_funcs = {
    'day': list,  # Assuming the day is the same for each basket
    'basket_id': list,
    'product_id': list,  # Aggregate product_ids into a list
    'quantity': list,   # Sum quantities
    'sales_value': list,  # Sum sales values
    'store_id': 'first',  # Use the first store_id (assuming it's the same for the basket)
    'retail_disc': list,  # Sum retail discounts
    'trans_time': 'first',  # Aggregate transaction times into a list
    'week_no': 'first',  # Use the first week_no (assuming it's consistent per basket)
    'coupon_disc': list,  # Sum coupon discounts
    'coupon_match_disc': list,  # Sum coupon match discounts
    'sales_value_eu':list,  # Sum sales values in EU
    'loyalty_card_price': list,  # Average loyalty card prices
    'non_loyalty_card_price': list,  # Average non-loyalty card prices
    'days_': 'first',  # Assuming days_ is the same for each basket
    'transaction_date': 'first',  # Use the first transaction date (assuming consistency)
    'manufacturer': list,  # List of manufacturers
    'department': list,  # List departments
    'brand': list,  # List brands
    'commodity_desc': list,  # List commodity descriptions
    'sub_commodity_desc': list,  # List sub-commodity descriptions
    'curr_size_of_product': list,  # List sizes of products
    'curr_size_of_product_value': list,  # List sizes of product values
    'curr_size_of_product_units': list  # List sizes of product units
}

# Group by household_key and basket_id and apply aggregations
grouped_df = merger.groupby(['household_key']).agg(agg_funcs).reset_index()
grouped_df

,household_key,day,basket_id,product_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc,sales_value_eu,loyalty_card_price,non_loyalty_card_price,days_,transaction_date,manufacturer,department,brand,commodity_desc,sub_commodity_desc,curr_size_of_product,curr_size_of_product_value,curr_size_of_product_units
0,1,"[51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 5...","[27601281299, 27601281299, 27601281299, 276012...","[825123, 831447, 840361, 845307, 852014, 85498...","[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, ...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",436,"[0.0, 0.0, -0.3, -0.62, -1.2, -1.3, -0.49, 0.0...",1456,8,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[4.27, 3.2, 1.17, 3.97, 2.99, 7.69, 2.68, 1.59...","[3.99, 2.99, 1.39, 4.33, 3.99, 8.49, 2.99, 1.4...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",51,2021-02-20,"[1179, 317, 69, 4084, 69, 1011, 159, 407, 2082...","[GROCERY, GROCERY, GROCERY, DELI, GROCERY, GRO...","[National, National, Private, National, Privat...","[SALD DRSNG/SNDWCH SPRD, CHEESE, EGGS, DELI ME...","[SEMI-SOLID SALAD DRESSING MAY, SHREDDED CHEES...","[30 OZ, 8 OZ, 1 DZ, , 56 OZ, , 16 OZ, 15 OZ,...","[30.0, 8.0, 1.0, nan, 56.0, nan, 16.0, 15.0, 2...","[ OZ, OZ, DZ, , OZ, , OZ, OZ, OZ, OZ,..."
1,2,"[103, 103, 103, 103, 103, 103, 103, 103, 103, ...","[28210649301, 28210649301, 28210649301, 282106...","[854852, 930118, 1077555, 1098066, 5567388, 55...","[1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, ...","[0.65, 4.47, 1.0, 0.79, 2.5, 2.5, 2.5, 5.0, 3....",401,"[0.0, -5.03, -0.59, -0.2, -2.19, -2.19, -2.19,...",1904,15,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -2.5, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.7, 4.78, 1.07, 0.85, 2.68, 2.68, 2.68, 5.35...","[0.65, 9.5, 1.59, 0.99, 4.69, 4.69, 4.69, 4.69...","[0.65, 4.47, 1.0, 0.79, 2.5, 2.5, 2.5, 2.5, 3....",103,2021-04-13,"[2, 2, 69, 69, 1208, 1208, 1208, 1208, 1323, 6...","[PRODUCE, PRODUCE, GROCERY, GROCERY, GROCERY, ...","[National, National, Private, Private, Nationa...","[TOMATOES, STONE FRUIT, MILK BY-PRODUCTS, BAKE...","[TOMATOES HOTHOUSE ON THE VINE, CHERRIES RED, ...","[13 LB, 2 LB, 16 OZ, 11 OZ, 12OZ/12PK, 12 OZ, ...","[13.0, 2.0, 16.0, 11.0, 12.0, 12.0, 12.0, 12.0...","[ LB, LB, OZ, OZ, OZ/PK, OZ, OZ, OZ, LB,..."
2,3,"[113, 113, 113, 113, 113, 113, 113, 113, 113, ...","[28344561779, 28344561779, 28344561779, 283445...","[866211, 878996, 882830, 904360, 921345, 93194...","[1, 1, 1, 1, 3, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, ...","[3.08, 1.64, 1.29, 0.99, 5.0, 2.08, 4.0, 1.69,...",401,"[-1.04, -0.55, 0.0, 0.0, -0.97, 0.0, 0.0, 0.0,...",1549,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.3, 1.75, 1.38, 1.06, 5.35, 2.23, 4.28, 1.81...","[4.12, 2.19, 1.29, 0.99, 1.99, 1.04, 2.0, 1.69...","[3.08, 1.64, 1.29, 0.99, 1.67, 1.04, 2.0, 1.69...",113,2021-04-23,"[2, 2, 764, 673, 1094, 1377, 1071, 910, 69, 2,...","[PRODUCE, PRODUCE, GROCERY, PRODUCE, MEAT-PCKG...","[National, National, National, National, Natio...","[GRAPES, GRAPES, WAREHOUSE SNACKS, VEGETABLES ...","[GRAPES WHITE, GRAPES RED, CANISTER POTATO/TOR...","[18 LB, 18 LB, 5.75 OZ, 24CT, 4.5 OZ, 15 OZ, 9...","[18.0, 18.0, 5.0, 24.0, 4.0, 15.0, 9.0, 20.0, ...","[ LB, LB, . OZ, CT, . OZ, OZ, OZ, OZ, LB,..."
3,4,"[104, 104, 104, 104, 104, 104, 104, 104, 104, ...","[28243317097, 28243317097, 28243317097, 282433...","[836163, 857849, 877523, 878909, 883932, 89142...","[2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, ...","[3.0, 0.44, 1.79, 1.5, 1.83, 3.59, 2.0, 0.99, ...",298,"[-2.58, -0.45, 0.0, -0.09, -0.66, 0.0, -0.89, ...",1452,16,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.21, 0.47, 1.92, 1.61, 1.96, 3.84, 2.14, 1.0...","[2.79, 0.89, 1.79, 1.59, 2.49, 3.59, 2.89, 1.1...","[1.5, 0.44, 1.79, 1.5, 1.83, 3.59, 2.0, 0.99, ...",104,2021-04-14,"[586, 71, 194, 69, 586, 1075, 69, 1529, 499, 1...","[GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, ...","[National, National, National, Private, Nation...","[COOKIES/CONES, MARGARINES, SPICES & EXTRACTS,...","[CHOCOLATE COVERED COOKIES, MARGARINE STICK, ...","[8.5 OZ, 16 OZ, 4.4 OZ, 13OZ/12CT, 16 OZ, 8 OZ...","[8.0, 16.0, 4.0, 13.0, 16.0, 8.0, 8.0, 6.0, 12...","[. OZ, OZ, . OZ, OZ/CT, OZ, OZ, OZ, OZ, ..."
4,5,"[85, 85, 87, 88, 88, 88, 97, 97, 97, 97, 97, 9...","[27997276369, 27997276369, 28023500778, 280241...","[938983, 5980822, 1012352, 825538, 1002499, 69...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, ...","[1.99, 2.49, 5.54, 7.59, 2.59, 3.5, 3.34, 6.49...",374,"[0.0, 0.0, -1.85, 0.0, -0.9, -0.49, -1.85, 0.0...",1540,13,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.13, 2.66, 5.93, 8.12, 2.77, 3.75, 3.57, 6.9...","[1.99, 2.49, 7.39, 7.59, 3.49, 3.99, 5.19, 6.4...","[1.99, 2.49, 5.54, 7.59, 2.59, 3.5, 3.34, 6.49...",85,2021-03-26,"[5143, 5143, 870, 1216, 410, 5268, 69, 397, 80...","[DRUG GM, DRUG GM, DRUG GM, MEAT-PCKGD, GROCER...","[National, National, National, National, Natio...","[GREETING CARDS/WRAP/PARTY SPLY, GREETING CARD...","[CARDS SEASONAL, CARDS SEASONAL, SUNBURN AFTER...","[ , , , 4 LB, 14 OZ, 16 OZ, 32.75 OZ, 29 OZ,...","[nan, nan, nan, 4.0, 14.0, 16.0, 32.0, 29.0, n...","[ , , , LB, OZ, OZ, . OZ, OZ, , , OZ,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,"[117, 117, 117, 117, 117, 117, 117, 117, 117, ...","[28391736778, 28391736778, 28391736778, 283917...","[840361, 852159, 871756, 886703, 899624, 91612...","[1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 6, 1, 1, 1, ...","[0.79, 3.71, 2.95, 1.09, 2.99, 5.32, 16.24, 1....",370,"[-0.6, 0.0, -0.74, 0.0, 0.0, -7.47, 0.0, -0.3,...",1345,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.85, 3.97, 3.16, 1.17, 3.2, 5.69, 17.38, 1.8...","[1.39, 3.71, 3.69, 1.09, 2.99, 6.4, 16.24, 1.9...","[0.79, 3.71, 2.95, 1.09, 2.99, 2.66, 16.24, 1....",117,2021-04-27,"[69, 2946, 317, 69, 69, 4314, 2908, 69, 1276, ...","[GROCERY, MEAT, GROCERY, GROCERY, PRODUCE, MEA...","[Private, National, National, Private, Private...","[EGGS, BEEF, SALD DRSNG/SNDWCH SPRD, MISC. DAI...","[EGGS - LARGE, CHOICE BEEF, SEMI-SOLID SALAD D...","[1 DZ, , 32 OZ, 17.5 OZ, 10 LB, , , 16OZ, 1...","[1.0, nan, 32.0, 17.0, 10.0, nan, nan, 16.0, 1...","[ DZ, , OZ, . OZ, LB, , , OZ, OZ, , LB..."
2496,2497,"[78, 78, 78, 78, 78, 80, 80, 80, 80, 80, 82, 8...","[27913035576, 27913035576, 27913035576, 279130...","[838220, 1037840, 1052294, 5569230, 8090537, 1...","[1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, ...","[25.33, 3.04, 29.34, 5.0, 3.34, 7.99, 5.0, 5.0...",339,"[0.0, 0.0, 0.0, -4.38, -1.25, 0.0, -4.38, -4.3...",1121,12,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[27.1, 3.25, 31.39, 5.35, 3.57, 8.55, 5.35, 5....","[25.33, 3.04, 29.34, 4.69, 4.59, 7.99, 4.69, 4...","[25.33, 3.04, 29.34, 2.5, 3.34, 7.99, 2.5, 2.5...",78,2021-03-19,"[539, 539, 539, 1208, 103, 2, 1208, 1208, 1208...","[DRUG GM, DRUG GM, DRUG GM, GROCERY, GROCERY, ...","[National, National, National, National, Natio...","[CIGARETTES, CIGARETTES, CIGARETTES, SOFT DRIN...","[CIGARETTES, CIGARETTES, CIGARETTES, SOFT DRIN...","[525345 CTN, 973875 PK, 522946 CTN, 12 OZ, 12...","[525345.0, 973875.0, 522946.0, 12.0, 12.0, 12....","[ CTN, PK, CTN, OZ, OZ, OZ, OZ, OZ, O..."
2497,2498,"[105, 105, 105, 105, 105, 105, 105, 105, 105, ...","[28243481507, 28243481507, 28243481507, 282434...","[824555, 835576, 901776, 904023, 911215, 91749...","[1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, ...","[0.1, 0.1, 2.69, 0.1, 0.1, 0.1, 0.1, 0.2, 0.1,...",309,"[-0.1, -0.1, -1.3, -0.1, -0.1, -0.1, -0.1, -0....",1823,16,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.11, 0.11, 2.88, 0.11, 0.11, 0.11, 0.11, 0.2...","[0.2, 0.2, 3.99, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,...","[0.1, 0.1, 2.69, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...",105,2021-04-15,"[1046, 1046, 436, 1046, 1046, 1046, 1046, 1046...","[GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, ...","[National, National, National, National, Natio...","[PWDR/CRYSTL DRNK MX, PWDR/CRYSTL DRNK MX, REF...","[SOFT DRINK POWDER POUCHES, SOFT DRINK POWDER ...","[L .15 OZ, 2 QT, 59 OZ, 2 QT, .13 OZ, .17 OZ...","[15.0, 2.0, 59.0, 2.0, 13.0, 17.0, 2.0, 14.0, ...","[L . OZ, QT, OZ, QT, . OZ, . OZ, QT, . O..."
2498,2499,"[70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 85, 8...","[27816885334, 27816885334, 27816885334, 278168...","[838186, 853197, 864143, 883665, 932949, 93383...","[1, 1, 6, 7, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, ...","[3.99, 1.5, 4.74, 19.53, 2.38, 4.9, 3.34, 3.35...",31782,"[0.0, -0.39, -0.6, -3.5, 0.0, -0.98, -0.65, 0....",1056,11,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[4.27, 1.61, 5.07, 20.9, 2.55, 5.24, 3.57, 3.5...","[3.99, 1.89, 0.89, 3.29, 2.38, 2.94, 3.99, 3.3...","[3.99, 1.5, 0.79, 2.79, 2.38, 2.45, 3.34, 3.35...",70,2021-03-11,"[1790, 1914, 69, 1046, 3869, 3705, 103, 3787, ...","[GROCERY, GROCERY, GROCERY, GROCERY, DELI, DEL...","[National, National, Private, National, Nation...","[BAKED SWEET GOODS, BAKED BREAD/BUNS/ROLLS, FL...","[SW GDS:DONUTS, RYE BREADS, FLUID MILK WHITE O...","[18.2 OZ, 16 OZ, 1 PT, 6 PK, , , 24 OZ, , 2...","[18.0, 16.0, 1.0, 6.0, nan, nan, 24.0, nan, 20...","[. OZ, OZ, PT, PK, , , OZ, , OZ, OZ, ..."
2499,2500,"[79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 7...","[27924907417, 27924907417, 27924982026, 279249...","[856455, 903476, 834102, 837751, 880797, 89301...","[1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[2.68, 5.79, 5.67, 2.99, 3.29, 1.97, 2.29, 3.4...",396,"[0.0, 0.0, 0.0, -0.8, 0.0, -1.02, 0.0, 0.0, -0...",1924,12,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.87, 6.2, 6.07, 3.2, 3.52, 2.11, 2.45, 3.73,...","[2.68, 5.79, 1.89, 3.79, 3.29, 2.99, 2.29, 3.4...","[2.68, 5.79, 1.89, 2.99, 3.29, 1.97, 2.29, 3.4...",79,2021-03-20,"[5068, 4952, 499, 794, 5072, 69, 69, 751, 194,...","[DRUG GM, DRUG GM, PRODUCE, GROCERY, DRUG GM, ...","[National, National, National, National, Natio...","[FEMININE HYGIENE, ANALGESICS, POPCORN, COLD C...","[FEM. HYGN.NAPKINS, ADULT ANALGESICS, POPCORN ...","[24 CT, , 3.0 OZ, 12.2 OZ, 15 OZ, 16OZ, 13 OZ...","[24.0, nan, 3.0, 12.0, 15.0, 16.0, 13.0, 84.0,...","[ CT, , . OZ, . OZ, OZ, OZ, OZ, CT REFIL, ...."

In [8]:
unique_departments = set(dept for sublist in grouped_df['department'] for dept in sublist)

# Iterate over each row and compute department quantities
for dept in unique_departments:
    grouped_df[dept + '_quantity'] = grouped_df.apply(
        lambda row: sum(q for d, q in zip(row['department'], row['quantity']) if d == dept),
        axis=1
    )


grouped_df

,household_key,day,basket_id,product_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc,sales_value_eu,loyalty_card_price,non_loyalty_card_price,days_,transaction_date,manufacturer,department,brand,commodity_desc,sub_commodity_desc,curr_size_of_product,curr_size_of_product_value,curr_size_of_product_units,DAIRY DELI_quantity,COUP/STR & MFG_quantity,PROD-WHS SALES_quantity,MEAT-PCKGD_quantity,RESTAURANT_quantity,SALAD BAR_quantity,HOUSEWARES_quantity,DELI_quantity,RX_quantity,GRO BAKERY_quantity,FLORAL_quantity,HBC_quantity,SEAFOOD-PCKGD_quantity,TRAVEL & LEISUR_quantity,ELECT &PLUMBING_quantity,MEAT-WHSE_quantity,SPIRITS_quantity,MISC SALES TRAN_quantity,NUTRITION_quantity,TOYS_quantity,GROCERY_quantity,CHARITABLE CONT_quantity,CHEF SHOPPE_quantity,GARDEN CENTER_quantity,PRODUCE_quantity,MISC. TRANS._quantity,GM MERCH EXP_quantity,PHARMACY SUPPLY_quantity,_quantity,KIOSK-GAS_quantity,MEAT_quantity,VIDEO RENTAL_quantity,SEAFOOD_quantity,DELI/SNACK BAR_quantity,POSTAL CENTER_quantity,PASTRY_quantity,COSMETICS_quantity,AUTOMOTIVE_quantity,CNTRL/STORE SUP_quantity,PHOTO_quantity,FROZEN GROCERY_quantity,VIDEO_quantity,PORK_quantity,DRUG GM_quantity
0,1,"[51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 5...","[27601281299, 27601281299, 27601281299, 276012...","[825123, 831447, 840361, 845307, 852014, 85498...","[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, ...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",436,"[0.0, 0.0, -0.3, -0.62, -1.2, -1.3, -0.49, 0.0...",1456,8,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[4.27, 3.2, 1.17, 3.97, 2.99, 7.69, 2.68, 1.59...","[3.99, 2.99, 1.39, 4.33, 3.99, 8.49, 2.99, 1.4...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",51,2021-02-20,"[1179, 317, 69, 4084, 69, 1011, 159, 407, 2082...","[GROCERY, GROCERY, GROCERY, DELI, GROCERY, GRO...","[National, National, Private, National, Privat...","[SALD DRSNG/SNDWCH SPRD, CHEESE, EGGS, DELI ME...","[SEMI-SOLID SALAD DRESSING MAY, SHREDDED CHEES...","[30 OZ, 8 OZ, 1 DZ, , 56 OZ, , 16 OZ, 15 OZ,...","[30.0, 8.0, 1.0, nan, 56.0, nan, 16.0, 15.0, 2...","[ OZ, OZ, DZ, , OZ, , OZ, OZ, OZ, OZ,...",0,0,0,117,3,13,0,68,0,0,1,0,0,0,0,0,0,2,19,0,1310,0,0,0,209,0,0,0,0,0,5,0,0,0,0,49,0,0,0,0,0,0,0,201
1,2,"[103, 103, 103, 103, 103, 103, 103, 103, 103, ...","[28210649301, 28210649301, 28210649301, 282106...","[854852, 930118, 1077555, 1098066, 5567388, 55...","[1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, ...","[0.65, 4.47, 1.0, 0.79, 2.5, 2.5, 2.5, 5.0, 3....",401,"[0.0, -5.03, -0.59, -0.2, -2.19, -2.19, -2.19,...",1904,15,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -2.5, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.7, 4.78, 1.07, 0.85, 2.68, 2.68, 2.68, 5.35...","[0.65, 9.5, 1.59, 0.99, 4.69, 4.69, 4.69, 4.69...","[0.65, 4.47, 1.0, 0.79, 2.5, 2.5, 2.5, 2.5, 3....",103,2021-04-13,"[2, 2, 69, 69, 1208, 1208, 1208, 1208, 1323, 6...","[PRODUCE, PRODUCE, GROCERY, GROCERY, GROCERY, ...","[National, National, Private, Private, Nationa...","[TOMATOES, STONE FRUIT, MILK BY-PRODUCTS, BAKE...","[TOMATOES HOTHOUSE ON THE VINE, CHERRIES RED, ...","[13 LB, 2 LB, 16 OZ, 11 OZ, 12OZ/12PK, 12 OZ, ...","[13.0, 2.0, 16.0, 11.0, 12.0, 12.0, 12.0, 12.0...","[ LB, LB, OZ, OZ, OZ/PK, OZ, OZ, OZ, LB,...",0,0,0,23,0,0,0,13,0,0,1,0,1,0,0,0,0,2,3,0,544,0,0,0,87,0,0,0,0,0,34,0,0,0,0,11,5,0,0,0,0,0,0,110
2,3,"[113, 113, 113, 113, 113, 113, 113, 113, 113, ...","[28344561779, 28344561779, 28344561779, 283445...","[866211, 878996, 882830, 904360, 921345, 93194...","[1, 1, 1, 1, 3, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, ...","[3.08, 1.64, 1.29, 0.99, 5.0, 2.08, 4.0, 1.69,...",401,"[-1.04, -0.55, 0.0, 0.0, -0.97, 0.0, 0.0, 0.0,...",1549,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.3, 1.75, 1.38, 1.06, 5.35, 2.23, 4.28, 1.81...","[4.12, 2.19, 1.29, 0.99, 1.99, 1.04, 2.0, 1.69...","[3.08, 1.64, 1.29, 0.99, 1.67, 1.04, 2.0, 1.69...",113,2021-04-23,"[2, 2, 764, 673, 1094, 1377, 1071, 910, 69, 2,...","[PRODUCE, PRODUCE, GROCERY, PRODUCE, MEAT-PCKG...","[National, National, National, National, Natio...","[GRAPES, GRAPES, WAREHOUSE SNACKS, VEGETABLES ...","[GRAPES WHITE, GRAPES RED, CANISTER POTATO/TOR...","[18 LB, 18 LB, 5.75 OZ, 24CT, 4.5 OZ, 15 OZ, 9...","[18.0, 18.0, 5.0, 24.0, 4.0, 15.0, 9.0, 20.0, ...","[ LB, LB, . OZ, CT, . OZ, OZ, OZ, OZ, LB,...",0,0,0,113,0,1,0,6,0,0,0,0,2,0,0,0,0,0,0,0,1251,0,0,0,40,0,0,0,0,6949,69,0,0,0,0,1,1,0,0,0,0,0,0,107
3,4,"[104, 104, 104, 104, 104, 104, 104, 104, 104, ...","[28243317097, 28243317097, 28243317097, 282433...","[836163, 857849, 877523, 878909, 883932, 89142...","[2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, ...","[3.0, 0.44, 1.79, 1.5, 1.83, 3.59, 2.0, 0.99, ...",298,"[-2.58, -0.45, 0.0, -0.09, -0.66, 0.0, -0.89, ...",1452,16,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.21, 0.47, 1.92, 1.61, 1.96, 3.84, 2.14, 1.0...","[2.79, 0.89, 1.79, 1.59, 2.49, 3.59, 2.89, 1.1...","[1.5, 0.44, 1.79, 1.5, 1.83, 3.59, 2.0, 0.99, ...",104,2021-04-14,"[586, 71, 194, 69, 586, 1075, 69, 1529, 499, 1...","[GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, ...","[National, National, National, Private, Nation...","[COOKIES/CONES, MARGARINES, SPICES & EXTRACTS,...","[CHOCOLATE COVERED COOKIES, MARGARINE STICK, ...","[8.5 OZ, 16 OZ, 4.4 OZ, 13OZ/12CT, 16 OZ, 8 OZ...","[8.0, 16.0, 4.0, 13.0, 16.0, 8.0, 8.0, 6.0, 12...","[. OZ, OZ, . OZ, OZ/CT, OZ, OZ, OZ, OZ, ...",0,0,0,34,0,0,0,3,0,0,0,0,3,0,0,0,0,0,1,0,289,0,0,0,3,0,0,0,0,0,10,0,0,0,0,0,2,0,0,0,0,0,0,37
4,5,"[85, 85, 87, 88, 88, 88, 97, 97, 97, 97, 97, 9...","[27997276369, 27997276369, 28023500778, 280241...","[938983, 5980822, 1012352, 825538, 1002499, 69...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, ...","[1.99, 2.49, 5.54, 7.59, 2.59, 3.5, 3.34, 6.49...",374,"[0.0, 0.0, -1.85, 0.0, -0.9, -0.49, -1.85, 0.0...",1540,13,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.13, 2.66, 5.93, 8.12, 2.77, 3.75, 3.57, 6.9...","[1.99, 2.49, 7.39, 7.59, 3.49, 3.99, 5.19, 6.4...","[1.99, 2.49, 5.54, 7.59, 2.59, 3.5, 3.34, 6.49...",85,2021-03-26,"[5143, 5143, 870, 1216, 410, 5268, 69, 397, 80...","[DRUG GM, DRUG GM, DRUG GM, MEAT-PCKGD, GROCER...","[National, National, National, National, Natio...","[GREETING CARDS/WRAP/PARTY SPLY, GREETING CARD...","[CARDS SEASONAL, CARDS SEASONAL, SUNBURN AFTER...","[ , , , 4 LB, 14 OZ, 16 OZ, 32.75 OZ, 29 OZ,...","[nan, nan, nan, 4.0, 14.0, 16.0, 32.0, 29.0, n...","[ , , , LB, OZ, OZ, . OZ, OZ, , , OZ,...",0,0,0,13,0,0,0,21,0,0,0,0,0,0,0,0,0,0,2,0,139,0,0,0,2,0,0,0,0,0,10,0,0,0,0,2,2,0,0,0,0,0,0,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,"[117, 117, 117, 117, 117, 117, 117, 117, 117, ...","[28391736778, 28391736778, 28391736778, 283917...","[840361, 852159, 871756, 886703, 899624, 91612...","[1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 6, 1, 1, 1, ...","[0.79, 3.71, 2.95, 1.09, 2.99, 5.32, 16.24, 1....",370,"[-0.6, 0.0, -0.74, 0.0, 0.0, -7.47, 0.0, -0.3,...",1345,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.85, 3.97, 3.16, 1.17, 3.2, 5.69, 17.38, 1.8...","[1.39, 3.71, 3.69, 1.09, 2.99, 6.4, 16.24, 1.9...","[0.79, 3.71, 2.95, 1.09, 2.99, 2.66, 16.24, 1....",117,2021-04-27,"[69, 2946, 317, 69, 69, 4314, 2908, 69, 1276, ...","[GROCERY, MEAT, GROCERY, GROCERY, PRODUCE, MEA...","[Private, National, National, Private, Private...","[EGGS, BEEF, SALD DRSNG/SNDWCH SPRD, MISC. DAI...","[EGGS - LARGE, CHOICE BEEF, SEMI-SOLID SALAD D...","[1 DZ, , 32 OZ, 17.5 OZ, 10 LB, , , 16OZ, 1...","[1.0, nan, 32.0, 17.0, 10.0, nan, nan, 16.0, 1...","[ DZ, , OZ, . OZ, LB, , , OZ, OZ, , LB...",0,0,0,91,0,0,0,37,0,0,0,0,2,0,0,0,1,12,6,0,1124,0,0,0,159,0,0,0,0,128411,246,0,12,0,2,27,0,0,0,0,1,0,0,173
2496,2497,"[78, 78, 78, 78, 78, 80, 80, 80, 80, 80, 82, 8...","[27913035576, 27913035576, 27913035576, 279130...","[838220, 1037840, 1052294, 5569230, 8090537, 1...","[1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, ...","[25.33, 3.04, 29.34, 5.0, 3.34, 7.99, 5.0, 5.0...",339,"[0.0, 0.0, 0.0, -4.38, -1.25, 0.0, -4.38, -4.3...",1121,12,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[27.1, 3.25, 31.39, 5.35, 3.57, 8.55, 5.35, 5....","[25.33, 3.04, 29.34, 4.69, 4.59, 7.99, 4.69, 4...","[25.33, 3.04, 29.34, 2.5, 3.34, 7.99, 2.5, 2.5...",78,2021-03-19,"[539, 539, 539, 1208, 103, 2, 1208, 1208, 1208...","[DRUG GM, DRUG GM, DRUG GM, GROCERY, GROCERY, ...","[National, National, National, National, Natio...","[CIGARETTES, CIGARETTES, CIGARETTES, SOFT DRIN...","[CIGARETTES, CIGARETTES, CIGARETTES, SOFT DRIN...","[525345 CTN, 973875 PK, 522946 CTN, 12 OZ, 12...","[525345.0, 973875.0, 522946.0, 12.0, 12.0, 12....","[ CTN, PK, CTN, OZ, OZ, OZ, OZ, OZ, O...",0,0,0,94,0,2,0,59,0,0,4,0,9,0,0,0,0,3,2,0,2062,0,0,0,445,0,0,0,0,58262,94,0,0,0,0,16,5,0,0,0,0,0,0,179
2497,2498,"[105, 105, 105, 105, 105, 105, 105, 105, 105, ...","[28243481507, 28243481507, 28243481507, 282434...","[824555, 835576, 901776, 904023, 911215, 91749...","[1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, ...","[0.1, 0.1, 2.69, 0.1, 0.1, 0.1, 0.1, 0.2, 0.1,...",309,"[-0.1, -0.1, -1.3, -0.1, -0.1, -0.1, -0.1, -0....",1823,16,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.11, 0.11, 2.88, 0.11, 0.11, 0.11, 0.11, 0.2...","[0.2, 0.2, 3.99, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,...","[0.1, 0.1, 2.69, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...",105,2021-04-15,"[1046, 1046, 436, 1046, 1046, 1046, 1046, 1046...","[GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, ...","[National, National, National, National, Natio...","[PWDR/CRYSTL DRNK MX, PWDR/CRYSTL DRNK MX, REF...","[SOFT DRINK POWDER POUCHES, SOFT DRINK POWDER ...","[L .15 OZ, 2 QT, 59 OZ, 2 QT, .13 OZ, .17 OZ...","[15.0, 2.0, 59.0, 2.0, 13.0, 17.0, 2.0, 14.0, ...","[L . OZ, QT, OZ, QT, . OZ, . OZ, QT, . O...",0,0,0,40,0,5,0,10,0,0,1,0,0,1,0,0,2,30384,20,0,703,0,0,0,55,0,0,0,0,0,6,0,0,0,0,19,1,0,0,0,0,0,0,92
2498,2499,"[70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 85, 8...","[27816885334, 27816885334, 27816885334, 278168...","[838186, 853197, 864143, 883665, 932949, 93383...","[1, 1, 6, 7, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, ...","[3.99, 1.5, 4.74, 19.53, 2.38, 4.9, 3.34, 3.35...",31782,"[0.0, -0.39, -0.6, -3.5, 0.0, -0.98, -0.65, 0....",1056,11,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[4.27, 1.61, 5.07, 20.9, 2.55, 5.24, 3.57, 3.5...","[3.99, 1.89, 0.89, 3.29, 2.38, 2.94, 3.99, 3.3...","[3.99, 1.5, 0.79, 2.79, 2.38, 2.45, 3.34, 3.35...",70,2021-03-11,"[1790, 1914, 69, 1046, 3869, 3705, 103, 3787, ...","[GROCERY, GROCERY, GROCERY, GROCERY, DELI, DEL...","[National, National, Private, National, Nation...","[BAKED SWEET GOODS, BAKED BREAD/BUNS/ROLLS, FL...","[SW GDS:DONUTS, RYE BREADS, FLUID MILK WHITE O...","[18.2 OZ, 16 OZ, 1 PT, 6 PK, , , 24 OZ, , 2...","[18.0, 16.0, 1.0, 6.0, nan, nan, 24.0, nan, 20...","[. OZ, OZ, PT, PK, , , OZ, , OZ, OZ, ...",0,0,0,71,0,0,0,8,0,0,5,0,0,2,0,0,0,70771,4,0,1228,0,0,0,57,1,0,0,0,71137,34,0,0,0,0,29,0,0,0,0,0,0,0,102
2499,2500,"[79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 7...","[27924907417, 27924907417, 27924982026, 279249...","[856455, 903476, 834102, 837751, 880797, 89301...","[1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[2.68, 5.79, 5.67, 2.99, 3.29, 1.97, 2.29, 3.4...",396,"[0.0, 0.0, 0.0, -0.8, 0.0, -1.02, 0.0, 0.0, -0...",1924,12,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.87, 6.2, 6.07, 3.2, 3.52, 2.11, 2.45, 3.73,...","[2.68, 5.79, 1.89, 3.79, 3.29, 2.99, 2.29, 3.4...","[2.68, 5.79, 1.89, 2.99, 3.29, 1.97, 2.29, 3.4...",79,2021-03-20,"[5068, 4952, 499, 794, 5072, 69, 69, 751, 194,...","[DRUG GM, DRUG GM, PRODUCE, GROCERY, DRUG GM, ...","[National, National, National, National, Natio...","[FEMININE HYGIENE, ANALGESICS, POPCORN, COLD C...","[FEM. HYGN.NAPKINS, ADULT ANALGESICS, POPCORN ...","[24 CT, , 3.0 OZ, 12.2 OZ, 15 OZ, 16OZ, 13 OZ...","[24.0, nan, 3.0, 12.0, 15.0, 16.0, 13.0, 84.0,...","[ CT, , . OZ, . OZ, OZ, OZ, OZ, CT REFIL, ....",0,0,0,65,0,0,0,15,0,0,0,0,2,0,0,0,0,8,15,0,1389,0,0,0,104,0,0,0,0,245258,28,0,9,0,0,5,3,0,0,0,0,0,0,464

In [9]:
from collections import Counter

selected_household = grouped_df[grouped_df['household_key'] == 1]

# Extract the department lists for the selected household
departments_list = selected_household['department'].iloc[0]
quantities_list = selected_household['quantity'].iloc[0]

# Create a dictionary to store total quantities per department
department_quantities = {}
for dept, qty in zip(departments_list, quantities_list):
    if dept in department_quantities:
        department_quantities[dept] += qty
    else:
        department_quantities[dept] = qty

# Display the total quantity per department
print("Total quantity per department for household_key 1:")
for department, total_qty in department_quantities.items():
    print(f"{department}: {total_qty}")

Total quantity per department for household_key 1:
GROCERY: 1310
DELI: 68
MEAT-PCKGD: 117
PASTRY: 49
PRODUCE: 209
DRUG GM: 201
 : 0
MEAT: 5
SALAD BAR: 13
NUTRITION: 19
MISC SALES TRAN: 2
RESTAURANT: 3
FLORAL: 1

In [10]:
grouped_df[grouped_df['household_key'] == 1]

,household_key,day,basket_id,product_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc,sales_value_eu,loyalty_card_price,non_loyalty_card_price,days_,transaction_date,manufacturer,department,brand,commodity_desc,sub_commodity_desc,curr_size_of_product,curr_size_of_product_value,curr_size_of_product_units,DAIRY DELI_quantity,COUP/STR & MFG_quantity,PROD-WHS SALES_quantity,MEAT-PCKGD_quantity,RESTAURANT_quantity,SALAD BAR_quantity,HOUSEWARES_quantity,DELI_quantity,RX_quantity,GRO BAKERY_quantity,FLORAL_quantity,HBC_quantity,SEAFOOD-PCKGD_quantity,TRAVEL & LEISUR_quantity,ELECT &PLUMBING_quantity,MEAT-WHSE_quantity,SPIRITS_quantity,MISC SALES TRAN_quantity,NUTRITION_quantity,TOYS_quantity,GROCERY_quantity,CHARITABLE CONT_quantity,CHEF SHOPPE_quantity,GARDEN CENTER_quantity,PRODUCE_quantity,MISC. TRANS._quantity,GM MERCH EXP_quantity,PHARMACY SUPPLY_quantity,_quantity,KIOSK-GAS_quantity,MEAT_quantity,VIDEO RENTAL_quantity,SEAFOOD_quantity,DELI/SNACK BAR_quantity,POSTAL CENTER_quantity,PASTRY_quantity,COSMETICS_quantity,AUTOMOTIVE_quantity,CNTRL/STORE SUP_quantity,PHOTO_quantity,FROZEN GROCERY_quantity,VIDEO_quantity,PORK_quantity,DRUG GM_quantity
0,1,"[51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 5...","[27601281299, 27601281299, 27601281299, 276012...","[825123, 831447, 840361, 845307, 852014, 85498...","[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, ...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",436,"[0.0, 0.0, -0.3, -0.62, -1.2, -1.3, -0.49, 0.0...",1456,8,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[4.27, 3.2, 1.17, 3.97, 2.99, 7.69, 2.68, 1.59...","[3.99, 2.99, 1.39, 4.33, 3.99, 8.49, 2.99, 1.4...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",51,2021-02-20,"[1179, 317, 69, 4084, 69, 1011, 159, 407, 2082...","[GROCERY, GROCERY, GROCERY, DELI, GROCERY, GRO...","[National, National, Private, National, Privat...","[SALD DRSNG/SNDWCH SPRD, CHEESE, EGGS, DELI ME...","[SEMI-SOLID SALAD DRESSING MAY, SHREDDED CHEES...","[30 OZ, 8 OZ, 1 DZ, , 56 OZ, , 16 OZ, 15 OZ,...","[30.0, 8.0, 1.0, nan, 56.0, nan, 16.0, 15.0, 2...","[ OZ, OZ, DZ, , OZ, , OZ, OZ, OZ, OZ,...",0,0,0,117,3,13,0,68,0,0,1,0,0,0,0,0,0,2,19,0,1310,0,0,0,209,0,0,0,0,0,5,0,0,0,0,49,0,0,0,0,0,0,0,201

## Join to HH

In [12]:
hh = pd.read_csv("C:/Users/aprataso/Downloads/final_data/treated/hh_treated.csv")
hh

,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc,household_key,marital_status,age_group,adult_category_size,has_kids,avg_age,avg_income,male,female
0,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,1,married,senior,2.0,NaN,65.0,42000,1,1
1,A,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,7,married,middle-aged,2.0,NaN,49.5,62000,1,1
2,U,25-34K,Unknown,2 Adults Kids,3,1,8,unknown,adult,2.0,True,29.5,29500,1,1
3,U,75-99K,Homeowner,2 Adults Kids,4,2,13,unknown,adult,2.0,True,29.5,87000,1,1
4,B,50-74K,Homeowner,Single Female,1,None/Unknown,16,single,middle-aged,1.0,False,49.5,62000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,2494,unknown,middle-aged,2.0,NaN,39.5,62000,1,1
797,A,75-99K,Homeowner,Unknown,3,1,2496,married,middle-aged,NaN,NaN,49.5,87000,0,0
798,U,35-49K,Unknown,Single Male,1,None/Unknown,2497,unknown,middle-aged,1.0,False,49.5,42000,1,0
799,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,2498,unknown,adult,2.0,NaN,29.5,62000,1,1
800,U,Under 15K,Unknown,2 Adults Kids,3,1,2499,unknown,adult,2.0,True,29.5,15000,1,1

In [17]:
clients = hh.merge(grouped_df, on='household_key', how='inner')
clients.head(2)

,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc,household_key,marital_status,age_group,adult_category_size,has_kids,avg_age,avg_income,male,female,day,basket_id,product_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc,sales_value_eu,loyalty_card_price,non_loyalty_card_price,days_,transaction_date,manufacturer,department,brand,commodity_desc,sub_commodity_desc,curr_size_of_product,curr_size_of_product_value,curr_size_of_product_units,DAIRY DELI_quantity,COUP/STR & MFG_quantity,PROD-WHS SALES_quantity,MEAT-PCKGD_quantity,RESTAURANT_quantity,SALAD BAR_quantity,HOUSEWARES_quantity,DELI_quantity,RX_quantity,GRO BAKERY_quantity,FLORAL_quantity,HBC_quantity,SEAFOOD-PCKGD_quantity,TRAVEL & LEISUR_quantity,ELECT &PLUMBING_quantity,MEAT-WHSE_quantity,SPIRITS_quantity,MISC SALES TRAN_quantity,NUTRITION_quantity,TOYS_quantity,GROCERY_quantity,CHARITABLE CONT_quantity,CHEF SHOPPE_quantity,GARDEN CENTER_quantity,PRODUCE_quantity,MISC. TRANS._quantity,GM MERCH EXP_quantity,PHARMACY SUPPLY_quantity,_quantity,KIOSK-GAS_quantity,MEAT_quantity,VIDEO RENTAL_quantity,SEAFOOD_quantity,DELI/SNACK BAR_quantity,POSTAL CENTER_quantity,PASTRY_quantity,COSMETICS_quantity,AUTOMOTIVE_quantity,CNTRL/STORE SUP_quantity,PHOTO_quantity,FROZEN GROCERY_quantity,VIDEO_quantity,PORK_quantity,DRUG GM_quantity
0,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,1,married,senior,2.0,NaN,65.0,42000,1,1,"[51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 5...","[27601281299, 27601281299, 27601281299, 276012...","[825123, 831447, 840361, 845307, 852014, 85498...","[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, ...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",436,"[0.0, 0.0, -0.3, -0.62, -1.2, -1.3, -0.49, 0.0...",1456,8,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[4.27, 3.2, 1.17, 3.97, 2.99, 7.69, 2.68, 1.59...","[3.99, 2.99, 1.39, 4.33, 3.99, 8.49, 2.99, 1.4...","[3.99, 2.99, 1.09, 3.71, 2.79, 7.19, 2.5, 1.49...",51,2021-02-20,"[1179, 317, 69, 4084, 69, 1011, 159, 407, 2082...","[GROCERY, GROCERY, GROCERY, DELI, GROCERY, GRO...","[National, National, Private, National, Privat...","[SALD DRSNG/SNDWCH SPRD, CHEESE, EGGS, DELI ME...","[SEMI-SOLID SALAD DRESSING MAY, SHREDDED CHEES...","[30 OZ, 8 OZ, 1 DZ, , 56 OZ, , 16 OZ, 15 OZ,...","[30.0, 8.0, 1.0, nan, 56.0, nan, 16.0, 15.0, 2...","[ OZ, OZ, DZ, , OZ, , OZ, OZ, OZ, OZ,...",0,0,0,117,3,13,0,68,0,0,1,0,0,0,0,0,0,2,19,0,1310,0,0,0,209,0,0,0,0,0,5,0,0,0,0,49,0,0,0,0,0,0,0,201
1,A,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,7,married,middle-aged,2.0,NaN,49.5,62000,1,1,"[23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 2...","[27255010658, 27255010658, 27255010658, 272550...","[865569, 886703, 889731, 893400, 995436, 10205...","[2, 1, 3, 4, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, ...","[3.38, 1.09, 2.64, 4.0, 3.91, 3.86, 1.36, 2.29...",322,"[-0.2, 0.0, -2.13, -1.56, 0.0, -1.93, -0.42, -...",1435,4,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.62, 1.17, 2.82, 4.28, 4.18, 4.13, 1.46, 2.4...","[1.79, 1.09, 1.59, 1.39, 3.91, 5.79, 0.89, 2.4...","[1.69, 1.09, 0.88, 1.0, 3.91, 3.86, 0.68, 2.29...",23,2021-01-23,"[418, 69, 69, 1251, 4680, 3050, 1251, 794, 69,...","[GROCERY, GROCERY, GROCERY, GROCERY, MEAT, MEA...","[National, Private, Private, National, Nationa...","[CONVENIENT BRKFST/WHLSM SNACKS, MISC. DAIRY, ...","[GRANOLA BARS, REFRIGERATED MEXICAN PRODUCTS, ...","[12 OZ, 17.5 OZ, 24 OZ, 14.75 OZ, , , 10.5OZ...","[12.0, 17.0, 24.0, 14.0, nan, nan, 10.0, 12.0,...","[ OZ, . OZ, OZ, . OZ, , , .OZ, . OZ/C, GA,...",0,0,0,26,0,0,0,33,0,0,1,0,0,0,0,0,0,0,7,0,1040,0,0,0,132,1,0,0,0,0,40,0,1,0,0,9,16,0,0,0,0,0,0,248

In [19]:
columns_to_drop = [
    'day', 'basket_id', 'product_id', 'sales_value',
    'store_id', 'retail_disc', 'trans_time', 'week_no', 'coupon_disc',
    'coupon_match_disc', 'loyalty_card_price',
    'non_loyalty_card_price', 'days_', 'transaction_date', 'manufacturer',
    'brand', 'commodity_desc', 'sub_commodity_desc',
    'curr_size_of_product', 'curr_size_of_product_value',
    'curr_size_of_product_units'

# Drop the specified columns from the DataFrame `clients`
clients_cleaned = clients.drop(columns=columns_to_drop)
clients_cleaned.head(2)

,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc,household_key,marital_status,age_group,adult_category_size,has_kids,avg_age,avg_income,male,female,quantity,sales_value_eu,department,DAIRY DELI_quantity,COUP/STR & MFG_quantity,PROD-WHS SALES_quantity,MEAT-PCKGD_quantity,RESTAURANT_quantity,SALAD BAR_quantity,HOUSEWARES_quantity,DELI_quantity,RX_quantity,GRO BAKERY_quantity,FLORAL_quantity,HBC_quantity,SEAFOOD-PCKGD_quantity,TRAVEL & LEISUR_quantity,ELECT &PLUMBING_quantity,MEAT-WHSE_quantity,SPIRITS_quantity,MISC SALES TRAN_quantity,NUTRITION_quantity,TOYS_quantity,GROCERY_quantity,CHARITABLE CONT_quantity,CHEF SHOPPE_quantity,GARDEN CENTER_quantity,PRODUCE_quantity,MISC. TRANS._quantity,GM MERCH EXP_quantity,PHARMACY SUPPLY_quantity,_quantity,KIOSK-GAS_quantity,MEAT_quantity,VIDEO RENTAL_quantity,SEAFOOD_quantity,DELI/SNACK BAR_quantity,POSTAL CENTER_quantity,PASTRY_quantity,COSMETICS_quantity,AUTOMOTIVE_quantity,CNTRL/STORE SUP_quantity,PHOTO_quantity,FROZEN GROCERY_quantity,VIDEO_quantity,PORK_quantity,DRUG GM_quantity
0,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,1,married,senior,2.0,NaN,65.0,42000,1,1,"[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, ...","[4.27, 3.2, 1.17, 3.97, 2.99, 7.69, 2.68, 1.59...","[GROCERY, GROCERY, GROCERY, DELI, GROCERY, GRO...",0,0,0,117,3,13,0,68,0,0,1,0,0,0,0,0,0,2,19,0,1310,0,0,0,209,0,0,0,0,0,5,0,0,0,0,49,0,0,0,0,0,0,0,201
1,A,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,7,married,middle-aged,2.0,NaN,49.5,62000,1,1,"[2, 1, 3, 4, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, ...","[3.62, 1.17, 2.82, 4.28, 4.18, 4.13, 1.46, 2.4...","[GROCERY, GROCERY, GROCERY, GROCERY, MEAT, MEA...",0,0,0,26,0,0,0,33,0,0,1,0,0,0,0,0,0,0,7,0,1040,0,0,0,132,1,0,0,0,0,40,0,1,0,0,9,16,0,0,0,0,0,0,248

In [21]:
import pandas as pd
import ast

# Sample data loading (replace with actual data)
# clients_cleaned = pd.read_csv('your_file.csv')

# Convert string representations of lists to actual lists if needed
clients_cleaned['department'] = clients_cleaned['department'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
clients_cleaned['sales_value_eu'] = clients_cleaned['sales_value_eu'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
clients_cleaned['quantity'] = clients_cleaned['quantity'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Convert lists within DataFrame columns to numeric values if necessary
clients_cleaned['sales_value_eu'] = clients_cleaned['sales_value_eu'].apply(lambda x: list(map(float, x)))
clients_cleaned['quantity'] = clients_cleaned['quantity'].apply(lambda x: list(map(float, x)))

# Initialize an empty list to collect rows
rows = []

# Iterate over each row in the DataFrame
for index, row in clients_cleaned.iterrows():
    household_key = row['household_key']
    departments = row['department']  # Ensure this is a list of department names
    sales_values = row['sales_value_eu']  # Ensure this is a list of sales values (numeric)
    quantities = row['quantity']  # Ensure this is a list of quantities (numeric)

    # Create a dictionary to store the total spending for each department
    total_spending = {}
    
    for dept, sales_value, quantity in zip(departments, sales_values, quantities):
        if dept not in total_spending:
            total_spending[dept] = 0
        total_spending[dept] += sales_value * quantity
    
    # Convert the dictionary to a DataFrame row
    spending_row = {'household_key': household_key}
    spending_row.update(total_spending)
    
    # Append the row to the list
    rows.append(spending_row)

# Convert the list of rows into a DataFrame
spending_per_department = pd.DataFrame(rows)

# Fill NaN values with 0 (for departments with no spending)
spending_per_department.fillna(0, inplace=True)


# Join the spending DataFrame to clients_cleaned
clients_cleaned = clients_cleaned.merge(spending_per_department, on='household_key', how='left')

# Rename spending columns to include '_spend'
spending_columns = spending_per_department.columns.drop('household_key')
spending_column_mapping = {col: f"{col}_spend" for col in spending_columns}

# Rename the columns
clients_cleaned.rename(columns=spending_column_mapping, inplace=True)

# Display the result
clients_cleaned.head()

,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc,household_key,marital_status,age_group,adult_category_size,has_kids,avg_age,avg_income,male,female,quantity,sales_value_eu,department,DAIRY DELI_quantity,COUP/STR & MFG_quantity,PROD-WHS SALES_quantity,MEAT-PCKGD_quantity,RESTAURANT_quantity,SALAD BAR_quantity,HOUSEWARES_quantity,DELI_quantity,RX_quantity,GRO BAKERY_quantity,FLORAL_quantity,HBC_quantity,SEAFOOD-PCKGD_quantity,TRAVEL & LEISUR_quantity,ELECT &PLUMBING_quantity,MEAT-WHSE_quantity,SPIRITS_quantity,MISC SALES TRAN_quantity,NUTRITION_quantity,TOYS_quantity,GROCERY_quantity,CHARITABLE CONT_quantity,CHEF SHOPPE_quantity,GARDEN CENTER_quantity,PRODUCE_quantity,MISC. TRANS._quantity,GM MERCH EXP_quantity,PHARMACY SUPPLY_quantity,_quantity,KIOSK-GAS_quantity,MEAT_quantity,VIDEO RENTAL_quantity,SEAFOOD_quantity,DELI/SNACK BAR_quantity,POSTAL CENTER_quantity,PASTRY_quantity,COSMETICS_quantity,AUTOMOTIVE_quantity,CNTRL/STORE SUP_quantity,PHOTO_quantity,FROZEN GROCERY_quantity,VIDEO_quantity,PORK_quantity,DRUG GM_quantity,GROCERY_spend,DELI_spend,MEAT-PCKGD_spend,PASTRY_spend,PRODUCE_spend,DRUG GM_spend,_spend,MEAT_spend,SALAD BAR_spend,NUTRITION_spend,MISC SALES TRAN_spend,RESTAURANT_spend,FLORAL_spend,COSMETICS_spend,MISC. TRANS._spend,SEAFOOD_spend,KIOSK-GAS_spend,SPIRITS_spend,CHEF SHOPPE_spend,SEAFOOD-PCKGD_spend,GARDEN CENTER_spend,DAIRY DELI_spend,AUTOMOTIVE_spend,CNTRL/STORE SUP_spend,COUP/STR & MFG_spend,TRAVEL & LEISUR_spend,GM MERCH EXP_spend,POSTAL CENTER_spend,FROZEN GROCERY_spend,DELI/SNACK BAR_spend,VIDEO_spend,RX_spend,PROD-WHS SALES_spend,MEAT-WHSE_spend,PHOTO_spend,PHARMACY SUPPLY_spend,TOYS_spend,GRO BAKERY_spend,HOUSEWARES_spend,HBC_spend,VIDEO RENTAL_spend
0,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,1,married,senior,2.0,NaN,65.0,42000,1,1,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, ...","[4.27, 3.2, 1.17, 3.97, 2.99, 7.69, 2.68, 1.59...","[GROCERY, GROCERY, GROCERY, DELI, GROCERY, GRO...",0,0,0,117,3,13,0,68,0,0,1,0,0,0,0,0,0,2,19,0,1310,0,0,0,209,0,0,0,0,0,5,0,0,0,0,49,0,0,0,0,0,0,0,201,3672.10,226.99,394.15,127.38,434.72,712.80,0.0,23.92,67.59,51.74,21.40,4.47,8.55,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,7,married,middle-aged,2.0,NaN,49.5,62000,1,1,"[2.0, 1.0, 3.0, 4.0, 1.0, 1.0, 2.0, 1.0, 1.0, ...","[3.62, 1.17, 2.82, 4.28, 4.18, 4.13, 1.46, 2.4...","[GROCERY, GROCERY, GROCERY, GROCERY, MEAT, MEA...",0,0,0,26,0,0,0,33,0,0,1,0,0,0,0,0,0,0,7,0,1040,0,0,0,132,1,0,0,0,0,40,0,1,0,0,9,16,0,0,0,0,0,0,248,2595.66,171.57,85.07,27.62,339.31,845.93,0.0,229.72,0.00,22.08,0.00,0.00,5.34,101.34,1.87,7.05,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,U,25-34K,Unknown,2 Adults Kids,3,1,8,unknown,adult,2.0,True,29.5,29500,1,1,"[1.0, 1.0, 1.0, 2.0, 3.0, 2.0, 1.0, 1.0, 1.0, ...","[3.73, 0.21, 4.27, 0.43, 12.17, 4.26, 0.94, 1....","[GROCERY, GROCERY, DRUG GM, GROCERY, MEAT-PCKG...",2,0,0,101,0,25,0,32,0,0,13,0,7,0,0,0,5,2,2,0,1693,0,2,4,182,0,0,0,0,65914,90,0,1,0,0,21,6,0,0,0,0,0,0,231,4332.98,152.36,436.25,112.60,438.86,1182.17,0.0,606.87,77.71,12.82,3.38,0.00,225.63,36.14,0.00,2.00,1723743.25,53.45,5.36,40.80,57.08,2.14,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,U,75-99K,Homeowner,2 Adults Kids,4,2,13,unknown,adult,2.0,True,29.5,87000,1,1,"[1.0, 1.0, 5.0, 1.0, 1.0, 2.0, 1.0, 3.0, 1.0, ...","[13.63, 2.99, 13.38, 16.04, 1.17, 5.01, 0.92, ...","[DRUG GM, GROCERY, GROCERY, DRUG GM, GROCERY, ...",0,0,0,124,0,3,0,31,0,0,4,0,6,0,0,0,0,461116,2,0,2342,0,0,0,116,0,0,0,0,1399474,1,0,0,0,0,5,8,1,0,0,0,0,0,596,9314.94,104.85,533.57,15.52,341.16,4782.13,0.0,20.47,10.80,3.54,30899529.93,0.00,50.24,51.38,0.00,0.00,63359349.72,0.00,0.00,25.53,0.00,0.00,7.69,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,B,50-74K,Homeowner,Single Female,1,None/Unknown,16,single,middle-aged,1.0,False,49.5,62000,0,1,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, ...","[1.81, 3.09, 3.73, 2.56, 2.12, 0.85, 6.4, 5.33...","[GROCERY, GROCERY, MEAT-PCKGD, GROCERY, PRODUC...",0,0,0,19,0,2,0,28,0,0,0,0,0,0,0,0,0,0,4,0,383,0,0,0,44,0,0,0,0,80628,16,0,0,0,0,26,0,0,0,0,0,0,0,50,1025.94,104.74,62.94,88.25,93.57,94.35,0.0,120.13,6.88,9.47,0.00,0.00,0.00,0.00,0.00,0.00,2083362.13,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
clients_cleaned.to_csv('C:/Users/aprataso/Downloads/final_data/treated/customer_info.csv')

confirm calculations

In [35]:
explore = clients_cleaned[['household_key', 'quantity', 'sales_value_eu', 'department', 'KIOSK-GAS_spend', 'KIOSK-GAS_quantity']]

In [36]:
pd.set_option('display.max_colwidth', None)
explore[explore['household_key'] == 8]

,household_key,quantity,sales_value_eu,department,KIOSK-GAS_spend,KIOSK-GAS_quantity
2,8,"[1.0, 1.0, 1.0, 2.0, 3.0, 2.0, 1.0, 1.0, 1.0, 4.0, 1.0, 4.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 4.0, 0.0, 0.0, 1.0, 2.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 9011.0, 13552.0, 1.0, 1.0, 1.0, 2.0, ...]","[3.73, 0.21, 4.27, 0.43, 12.17, 4.26, 0.94, 1.49, 4.27, 2.53, 1.92, 2.95, 3.09, 0.63, 1.26, 12.78, 5.97, 0.21, 1.7, 1.61, 2.96, 0.63, 3.52, 0.21, 2.87, 4.04, 1.55, 2.88, 2.24, 5.34, 0.21, 3.95, 12.39, 2.13, 0.21, 2.02, 2.13, 6.4, 1.79, 4.04, 3.84, 1.59, 0.21, 0.9, 0.21, 0.63, 2.99, 3.21, 2.14, 2.13, 3.25, 1.26, 3.2, 2.14, 5.35, 2.66, 6.4, 2.97, 1.61, 1.79, 3.73, 0.21, 1.78, 3.84, 1.81, 3.41, 3.41, 3.41, 3.41, 1.06, 2.12, 0.0, 0.0, 2.68, 5.35, 2.68, 3.73, 3.16, 1.06, 1.06, 4.27, 2.13, 5.23, 18.18, 4.27, 2.68, 3.75, 2.66, 3.73, 2.01, 2.01, 5.34, 2.68, 6.41, 19.27, 28.84, 1.17, 4.27, 1.07, 2.08, ...]","[GROCERY, GROCERY, DRUG GM, GROCERY, MEAT-PCKGD, PRODUCE, GROCERY, GROCERY, MEAT-PCKGD, PRODUCE, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, MEAT, MEAT, GROCERY, PRODUCE, GROCERY, PRODUCE, GROCERY, MEAT-PCKGD, GROCERY, DRUG GM, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, GROCERY, GROCERY, MEAT, GROCERY, GROCERY, GROCERY, GROCERY, MEAT-PCKGD, GROCERY, GROCERY, DRUG GM, PRODUCE, GROCERY, GROCERY, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, GROCERY, PRODUCE, PRODUCE, GROCERY, GROCERY, MEAT-PCKGD, DRUG GM, MEAT-PCKGD, GROCERY, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, DRUG GM, DRUG GM, , , GROCERY, GROCERY, GROCERY, DRUG GM, DRUG GM, DRUG GM, DRUG GM, GROCERY, GROCERY, GROCERY, DRUG GM, GROCERY, GROCERY, GROCERY, DRUG GM, DRUG GM, GROCERY, GROCERY, GROCERY, GROCERY, GROCERY, KIOSK-GAS, KIOSK-GAS, GROCERY, GROCERY, GROCERY, GROCERY, ...]",1723743.25,65914

In [37]:
def combine_lists(row):
    quantities = row['quantity']
    sales = row['sales_value_eu']
    departments = row['department']
    return pd.DataFrame({
        'quantity': quantities,
        'sales_value_eu': sales,
        'department': departments
    })

# Apply the function to each row and concatenate results
combined_df = pd.concat(explore.apply(combine_lists, axis=1).tolist(), ignore_index=True)
combined_df

         quantity  sales_value_eu department
0             1.0            4.27    GROCERY
1             1.0            3.20    GROCERY
2             1.0            1.17    GROCERY
3             1.0            3.97       DELI
4             1.0            2.99    GROCERY
...           ...             ...        ...
1427298       1.0            2.77    GROCERY
1427299       1.0            1.61    GROCERY
1427300       1.0            3.73     PASTRY
1427301       1.0            3.09    GROCERY
1427302       1.0            1.61    GROCERY

[1427303 rows x 3 columns]

In [38]:
combined_df[combined_df['department'] == 'KIOSK-GAS']

         quantity  sales_value_eu department
3107       9011.0           19.27  KIOSK-GAS
3108      13552.0           28.84  KIOSK-GAS
3161      12474.0           27.08  KIOSK-GAS
3235      11706.0           30.68  KIOSK-GAS
3878          1.0           26.75  KIOSK-GAS
...           ...             ...        ...
1425255   18379.0           38.52  KIOSK-GAS
1426250   13373.0           33.18  KIOSK-GAS
1426474   23371.0           60.99  KIOSK-GAS
1426669   10421.0           21.40  KIOSK-GAS
1426765   23972.0           55.64  KIOSK-GAS

[13053 rows x 3 columns]