In [25]:
import pandas as pd

In [26]:
transaction = pd.read_csv("C:/Users/aprataso/Downloads/final_data/transaction_data_enriched.csv")
prod = pd.read_csv("C:/Users/aprataso/Downloads/final_data/product_enriched.csv")

In [27]:
merger = transaction.merge(prod, on = 'product_id', how = 'left')

In [28]:
merger

,household_key,basket_id,day,product_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,...,days_,transaction_date,manufacturer,department,brand,commodity_desc,sub_commodity_desc,curr_size_of_product,curr_size_of_product_value,curr_size_of_product_units
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,...,1,2021-01-01,69,PRODUCE,Private,POTATOES,POTATOES RUSSET (BULK&BAG),5 LB,5.0,LB
1,2375,26984851472,1,1033142,1,0.82,364,0.00,1631,1,...,1,2021-01-01,2,PRODUCE,National,ONIONS,ONIONS SWEET (BULK&BAG),40 LB,40.0,LB
2,2375,26984851472,1,1036325,1,0.99,364,-0.30,1631,1,...,1,2021-01-01,69,PRODUCE,Private,VEGETABLES - ALL OTHERS,CELERY,,NaN,
3,2375,26984851472,1,1082185,1,1.21,364,0.00,1631,1,...,1,2021-01-01,2,PRODUCE,National,TROPICAL FRUIT,BANANAS,40 LB,40.0,LB
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,...,1,2021-01-01,69,PRODUCE,Private,ORGANICS FRUIT & VEGETABLES,ORGANIC CARROTS,1 LB,1.0,LB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2595727,1598,42305362535,711,92130,1,0.99,3228,0.00,1520,102,...,711,2022-12-12,560,GROCERY,National,MARGARINES,MARGARINE: TUBS AND BOWLS,16 OZ,16.0,OZ
2595728,1598,42305362535,711,114102,1,8.89,3228,0.00,1520,102,...,711,2022-12-12,2398,GROCERY,National,BEERS/ALES,BEERALEMALT LIQUORS,12 OZ,12.0,OZ
2595729,1598,42305362535,711,133449,1,6.99,3228,0.00,1520,102,...,711,2022-12-12,2468,GROCERY,National,BEERS/ALES,BEERALEMALT LIQUORS,12 OZ,12.0,OZ
2595730,1598,42305362535,711,6923644,1,4.50,3228,-0.49,1520,102,...,711,2022-12-12,2390,GROCERY,National,BEERS/ALES,BEERALEMALT LIQUORS,4PK/10 OZ,4.0,PK/ OZ
2595731,1598,42305362535,711,14055192,1,6.99,3228,0.00,1520,102,...,711,2022-12-12,2536,GROCERY,National,MISC WINE,BEERALEMALT LIQUORS,6PK/11.2OZ,6.0,PK/.OZ

In [29]:
# Count the number of times each department was purchased per basket_id
counts = merger.groupby(['basket_id', 'department']).size().reset_index(name='count')
counts

          basket_id department  count
0       26984851472    PRODUCE      5
1       26984851516    DRUG GM      1
2       26984851516    GROCERY      5
3       26984896261    GROCERY      3
4       26984896261       MEAT      1
...             ...        ...    ...
690398  42302712298     PASTRY      1
690399  42302712298    PRODUCE      2
690400  42305362497    DRUG GM      2
690401  42305362497    GROCERY      3
690402  42305362535    GROCERY      9

[690403 rows x 3 columns]

In [30]:
# Pivot the table to have departments as columns
pivot_counts = counts.pivot_table(index='basket_id', columns='department', values='count', fill_value=0)

In [32]:
# Reset index to make basket_id a column again
pivot_counts = pivot_counts.reset_index()

# Merge with the original DataFrame
final_merged = pd.merge(transaction, pivot_counts, on='basket_id', how='left')

MemoryError: Unable to allocate 19.8 MiB for an array with shape (2595732,) and data type int64

In [ ]:
final_merged = final_merged.groupby('basket_id')

In [ ]:
final_merged